"""Hand-written explanations for walkthrough files 14-29 (Phase 3: indexer).

Each dict maps a 0-based LINE NUMBER to the plain-English explanation that will
be rendered under that line. The code itself is read from the source file at
build time, so the dicts below must cover every line.
"""

FILES = [
    # ── FILE 14: src/indexer/run_index.py ───────────────────────────────────────
    {
        "out": "14-run-index-py.html",
        "src": "src/indexer/run_index.py",
        "title": "Walkthrough 14: src/indexer/run_index.py",
        "prev": "13-clean-py.html",
        "next": "15-api-index-py.html",
        "notes": {
            0: "Module docstring: computes daily, weekly, and monthly APIx index tables from cleaned_flights.",
            1: "",
            2: "Docstring: reads the full cleaned_flights table, builds the weighted basket index...",
            3: "...and writes the result to daily_index, weekly_index, and monthly_index tables.",
            4: "",
            5: "Docstring: usage section.",
            6: "Usage example: rebuild all indices via the module.",
            7: "Usage example: point the rebuild at a custom database file.",
            8: "Closes the module docstring.",
            9: "Imports argparse for the --db command-line flag.",
            10: "Imports logging for status messages.",
            11: "Imports sys — enables the stdout logging handler.",
            12: "Imports Path for filesystem paths.",
            13: "",
            14: "Opens the import block from src.indexer.api_index.",
            15: "compute_daily_index — the 36-cell daily composite basket.",
            16: "compute_rolling_index — 7-day or 30-day smoothing of daily values.",
            17: "load_active_windows — the lead windows the index should be built for.",
            18: "load_estimator_config — estimator names and trim fractions.",
            19: "load_index_config — the index section of indexer.yaml.",
            20: "load_route_weights — the normalised route weights.",
            21: "load_window_weights — the booking lead-time shares.",
            22: "read_cleaned_flights — loads cleaned rows as a DataFrame.",
            23: "route_price_per_day — collapses fares to one price per cell.",
            24: "write_index — saves an index table back to SQLite.",
            25: "Closes the import block.",
            26: "Imports get_connection and init_db from the storage layer.",
            27: "",
            28: "Creates the module-level logger.",
            29: "",
            30: "",
            31: "Defines _setup_logging: configures console logging for the CLI.",
            32: "Calls logging.basicConfig.",
            33: "Show INFO level and above.",
            34: "Format: timestamp | level | name | message.",
            35: "Time format HH:MM:SS.",
            36: "Directs output to stdout via a StreamHandler.",
            37: "Closes basicConfig.",
            38: "",
            39: "",
            40: "Defines run_index: the whole build pipeline; returns per-table row counts.",
            41: "Creates the tables if they do not exist.",
            42: "",
            43: "Loads cleaned flights as a DataFrame.",
            44: "If there are no cleaned rows at all...",
            45: "...log a warning...",
            46: "...and return all-zero counts (nothing to index).",
            47: "",
            48: "Loads the normalised route weights (sum 1.0).",
            49: "Loads the window shares — the second leg of the basket.",
            50: "Reads the rounding precision, default 2 decimals.",
            51: "Reads the active lead windows (1/7/30).",
            52: "Loads the estimator settings (names, trims, price method).",
            53: "",
            54: "Logs the start of the run.",
            55: "Logs the route count and total normalised weight (~1.0).",
            56: "Logs the booking lead-time shares.",
            57: "Logs the active lead windows.",
            58: "Logs the route price collapse method.",
            59: "Opens the multi-line estimator logger call.",
            60: "Log string describing both estimators and their trims.",
            61: "Aggregation estimator argument.",
            62: "Aggregation trim fraction argument.",
            63: "Rolling estimator argument.",
            64: "Rolling trim fraction argument.",
            65: "Closes the log call.",
            66: "",
            67: "Collapses cleaned rows to one fare per (route, window, date) cell.",
            68: "If no price rows survive the cleaning filter...",
            69: "...log a warning...",
            70: "...and return zero counts.",
            71: "Keeps only cells whose lead window is active.",
            72: "Still empty — no data for any active window...",
            73: "...log a warning with the window list...",
            74: "...and return zero counts.",
            75: "Logs how many price rows will be indexed.",
            76: "",
            77: "Builds the daily composite index over the basket.",
            78: "Positional arguments: prices, weights, window weights, rounding.",
            79: "Aggregation estimator from config.",
            80: "Trim fraction for the trimmed estimators.",
            81: "Closes the daily call.",
            82: "Builds the weekly index: a 7-day rolling of the daily values.",
            83: "Arguments: daily frame, 7-day window, rounding.",
            84: "Rolling estimator from config.",
            85: "Rolling trim fraction.",
            86: "Closes the weekly call.",
            87: "Builds the monthly index: a 30-day rolling of the daily values.",
            88: "Arguments: daily frame, 30-day window, rounding.",
            89: "Same rolling estimator.",
            90: "Same rolling trim fraction.",
            91: "Closes the monthly call.",
            92: "",
            93: "Writes the daily table, capturing the row count.",
            94: "Writes the weekly table, capturing the row count.",
            95: "Writes the monthly table, capturing the row count.",
            96: "",
            97: "Logs the completion summary with all three counts.",
            98: "Returns the counts dict (used by tests and the CLI).",
            99: "",
            100: "",
            101: "Defines main: the CLI entry point.",
            102: "Creates the argument parser with a description.",
            103: "Registers the optional --db flag overriding the database path.",
            104: "Parses the arguments.",
            105: "",
            106: "Configures logging before doing any work.",
            107: "Runs the pipeline for the given database.",
            108: "",
            109: "",
            110: "Runs main only when this module is executed directly.",
            111: "Calls main, running the index rebuild from the command line.",
        },
    },
    # ── FILE 15: src/indexer/api_index.py ───────────────────────────────────────
    {
        "out": "15-api-index-py.html",
        "src": "src/indexer/api_index.py",
        "title": "Walkthrough 15: src/indexer/api_index.py",
        "prev": "14-run-index-py.html",
        "next": "16-run-smoke-py.html",
        "notes": {
            0: "Module docstring: the APIx index builder — one composite headline from a 36-cell basket.",
            1: "",
            2: "Docstring: core math, per cell = route × lead window.",
            3: "Docstring: index(t, r, w) = today's cell price / base-day cell price × 100.",
            4: "Docstring: APIx(t) = sum over present cells of (cell index × route weight × window weight).",
            5: "",
            6: "Docstring: a single shared base date anchors every cell...",
            7: "...so t+1 / t+7 / t+30 are directly comparable (no per-window base).",
            8: "Docstring: the cell price is the MEDIAN fare on each (route, window, date)...",
            9: "...so a single ultra-cheap fare no longer drags a cell down.",
            10: "Docstring: routes that lose data are carried forward from the last known fare.",
            11: "Docstring: weights re-balance only over the cells present on each date...",
            12: "...so a late-starting window expands the basket cleanly.",
            13: "",
            14: "Docstring: the core functions operate on pandas DataFrames for easy offline testing...",
            15: "...while thin wrappers handle SQLite I/O.",
            16: "Closes the module docstring.",
            17: "Imports logging for status messages.",
            18: "Imports Path to resolve the config file location.",
            19: "",
            20: "Imports numpy for array and rolling math.",
            21: "Imports pandas for all DataFrame work.",
            22: "Imports yaml for reading indexer.yaml.",
            23: "",
            24: "Imports aggregate and weighted_trimmed_mean from the estimators module.",
            25: "Imports get_connection from the storage layer.",
            26: "",
            27: "Creates the module-level logger.",
            28: "",
            29: "CONFIG_PATH: resolves config/indexer.yaml relative to this file (up three parents to the repo root).",
            30: "",
            31: "INDEX_COLUMNS: the canonical column order shared by every index table.",
            32: "index_date — the date the observation applies to.",
            33: "lead_window_days — the booking window (1, 7, or 30).",
            34: "route — the city-pair route.",
            35: "weight — the cell weight (route weight × window weight).",
            36: "route_price — the collapsed fare for the cell on this date.",
            37: "route_index — the cell's index vs its own base fare (base = 100).",
            38: "aggregate_index — the composite headline, identical for every row of a date.",
            39: "base_period — the date each cell's base fare comes from.",
            40: "Closes the INDEX_COLUMNS list.",
            41: "",
            42: "INDEX_TABLES: the only table names write_index will accept.",
            43: "",
            44: "INSERT_SQL: parameterised insert template for index rows (opened).",
            45: "INSERT INTO the named table.",
            46: "The eight column names...",
            47: "...continued.",
            48: "Eight ? placeholders for the eight columns.",
            49: "Closes the SQL template.",
            50: "",
            51: "",
            52: "Defines load_index_config: reads the index: section of indexer.yaml.",
            53: "Docstring.",
            54: "Uses the supplied path, or falls back to CONFIG_PATH.",
            55: "Opens the YAML file (with-block closes it).",
            56: "Returns the index sub-dict, or an empty dict if missing.",
            57: "",
            58: "",
            59: "Defines load_route_weights: reads and normalises route weights to sum 1.0.",
            60: "Docstring.",
            61: "Grabs the raw weights dict from the config.",
            62: "Sums the raw weights.",
            63: "Guard: empty or non-positive totals...",
            64: "...raise a clear ValueError.",
            65: "Normalises each weight by the total.",
            66: "",
            67: "",
            68: "Defines load_window_weights: reads the booking lead-time shares.",
            69: "Docstring (first part): normalise them to sum 1.0.",
            70: "",
            71: "Docstring: these are the window leg of the 36-cell basket...",
            72: "...each cell's weight = route weight × window weight.",
            73: "Closes the docstring.",
            74: "Reads window_weights from config, defaulting to the 0.2/0.3/0.5 shares.",
            75: "Sums the raw shares.",
            76: "Guard: empty or non-positive totals...",
            77: "...raise a clear ValueError.",
            78: "Normalises to sum 1.0, forcing keys to int.",
            79: "",
            80: "",
            81: "Defines load_active_windows: which lead windows the index is built for.",
            82: "Docstring (defaults to t+1, t+7, t+30).",
            83: "Reads from config, defaulting to [1, 7, 30].",
            84: "Returns the windows as ints.",
            85: "",
            86: "",
            87: "Defines load_estimator_config: reads the estimator settings from config.",
            88: "Docstring (first part).",
            89: "",
            90: "Docstring: returns the aggregation estimator + trim (daily headline)...",
            91: "...the rolling estimator + trim (weekly/monthly smoothing)...",
            92: "...and the route-price collapse method.",
            93: "Closes the docstring.",
            94: "Loads the base index config once.",
            95: "Builds and returns the settings dict, filling defaults.",
            96: "aggregation_estimator, default weighted_mean.",
            97: "aggregation_trim_frac, default 0.10.",
            98: "rolling_estimator, default mean.",
            99: "rolling_trim_frac, default 0.10.",
            100: "route_price_method, default median.",
            101: "Closes the settings dict.",
            102: "",
            103: "",
            104: "Defines read_cleaned_flights: loads the whole cleaned_flights table as a DataFrame.",
            105: "Docstring.",
            106: "Opens a connection (default database unless a path is given).",
            107: "try block so the connection is always closed.",
            108: "Reads the entire table with pandas.read_sql.",
            109: "finally: always runs...",
            110: "...and closes the connection.",
            111: "",
            112: "",
            113: "ROUTE_PRICE_METHODS: the only allowed cell-price collapses.",
            114: "",
            115: "",
            116: "Defines route_price_per_day: one fare per (route, window, date) cell.",
            117: "Docstring (first part).",
            118: "",
            119: "Docstring: the method picks how the scraped fares in a cell combine:",
            120: "Docstring: min — the classic lowest-fare cell price.",
            121: "Docstring: median — robust centre (default); a single ultra-cheap fare...",
            122: "...no longer drags the cell down.",
            123: "",
            124: "Docstring: outlier rows (is_outlier == 1) are excluded from the price.",
            125: "Docstring: missing dates within a (route, window) span are carried forward...",
            126: "...from the last known fare, so a coverage gap...",
            127: "...no longer drags the aggregate down for no economic reason.",
            128: "Closes the docstring.",
            129: "Validates the method against ROUTE_PRICE_METHODS.",
            130: "Disallowed method: raise...",
            131: "...a clear ValueError naming the allowed choices.",
            132: "Works on a copy so the caller's frame is untouched.",
            133: "",
            134: "Drops rows with a null total_fare.",
            135: "Only filters outliers if the column exists (fixtures may omit it).",
            136: "Excludes outlier rows from the price.",
            137: "Opens the group-and-collapse pipeline...",
            138: "",
            139: "...group by route, lead window, and scrape date, then take total_fare...",
            140: "...apply the chosen collapse (min or median)...",
            141: "...flatten the group keys back to columns...",
            142: "...and rename total_fare to route_price.",
            143: "Closes the chained call.",
            144: "Sorts by route, window, and date for a stable carry-forward.",
            145: "Forward-fills missing dates and returns the result.",
            146: "Defines _carry_forward_missing_dates: fills calendar gaps per (route, window) span.",
            147: "",
            148: "",
            149: "Docstring (first part).",
            150: "Docstring: fills every calendar day between a group's first and last observed date...",
            151: "",
            152: "...dates before the first observation stay missing (nothing to carry from).",
            153: "Closes the docstring.",
            154: "Empty input: return it unchanged.",
            155: "Returns early.",
            156: "Accumulator of per-group chunks.",
            157: "",
            158: "Loops over each (route, window) group (group keys unused).",
            159: "Puts scrape_date in the index.",
            160: "Opens the calendar construction...",
            161: "...day by day...",
            162: "...formatted as YYYY-MM-DD strings.",
            163: "Reindexes to the calendar, then forward-fills the gaps.",
            164: "Resets the index, renaming it back to scrape_date.",
            165: "Saves the filled chunk.",
            166: "Concatenates all the chunks back together.",
            167: "",
            168: "Keeps only the original columns.",
            169: "Defines compute_daily_index: the core 36-cell daily basket calculation.",
            170: "",
            171: "",
            172: "Parameter: the prices DataFrame.",
            173: "Parameter: the route weights dict.",
            174: "Parameter: window weights dict (None means equal shares).",
            175: "Parameter: rounding precision.",
            176: "Parameter: the aggregation estimator name.",
            177: "Parameter: the trim fraction.",
            178: "Return type: a daily-index DataFrame.",
            179: "Docstring (first part).",
            180: "Docstring: each cell is priced against its OWN base fare — the fare on...",
            181: "",
            182: "...the shared base date (the first date with ANY data) when the cell...",
            183: "...existed then. A cell absent then uses its first observed fare instead...",
            184: "...and joins the basket at 100 on its own start date, so a mid-scrape...",
            185: "...window expands the basket without jerking the headline.",
            186: "Docstring: cell weight = route weight × window weight...",
            187: "",
            188: "...when window_weights is None the active windows share equal weight...",
            189: "...and the aggregate re-balances over the cells present on each date...",
            190: "...aggregate_index is the single composite headline...",
            191: "...identical for every row of a given date.",
            192: "Docstring: the aggregate uses the named estimator (see estimators module)...",
            193: "",
            194: "...weighted_mean is classic Laspeyres; trimmed/median are robust alternatives.",
            195: "Closes the docstring.",
            196: "Empty input: return an empty frame with the canonical schema.",
            197: "Returns early.",
            198: "If no window weights were provided...",
            199: "...infer the active windows from the data...",
            200: "",
            201: "...and give each equal weight (empty dict when none).",
            202: "cell_weight: the 36-cell basket — one entry per (route, window)...",
            203: "...value = route weight × window weight.",
            204: "",
            205: "For every route...",
            206: "...and every window...",
            207: "Closes the comprehension.",
            208: "base_date: the first date with ANY data (the shared anchor).",
            209: "base: each cell's price on the shared base date...",
            210: "",
            211: "...indexed by (route, window)...",
            212: "...picking the route_price column.",
            213: "Comment: fallback base for cells absent on the shared base date.",
            214: "Comment: they use their own first observation — joining the basket at 100 later.",
            215: "first_price: each cell's earliest observed fare...",
            216: "...sorting by scrape_date first...",
            217: "...then grouping by (route, window)...",
            218: "...and taking the first value.",
            219: "Closes the call.",
            220: "first_date: each cell's earliest observed date...",
            221: "...grouping by (route, window)...",
            222: "Closes the call.",
            223: "rows: master accumulator across all dates.",
            224: "Loops over each unique date, sorted.",
            225: "",
            226: "day_data: today's prices indexed by (route, window)...",
            227: "...continued...",
            228: "...picking the route_price column.",
            229: "route_indices: the present cells' index values.",
            230: "cells: the present cells' weights.",
            231: "",
            232: "date_rows: the output row dicts for this date.",
            233: "Loops over every (route, window) cell in the basket.",
            234: "Skips cells with no observation today.",
            235: "Continues.",
            236: "Optimistically assumes the shared base date.",
            237: "The cell key.",
            238: "Looks up the cell's base fare.",
            239: "Cell has no base on the shared date...",
            240: "...and no first observation either — skip it.",
            241: "Continues.",
            242: "Falls back to the cell's own first fare.",
            243: "Records that date as the cell's base_period.",
            244: "Skips cells with a non-positive base fare (division guard).",
            245: "Continues.",
            246: "route_index = today's price / base price × 100.",
            247: "Collects the cell index...",
            248: "...and its cell weight.",
            249: "Opens the row-dict construction.",
            250: "index_date.",
            251: "lead_window_days.",
            252: "route.",
            253: "weight — the cell weight.",
            254: "route_price — today's price.",
            255: "route_index — rounded.",
            256: "aggregate_index — filled in below (None for now).",
            257: "base_period — this cell's own base date.",
            258: "Closes the row dict.",
            259: "Closes the append call.",
            260: "Aggregates the present cells into the composite headline, rounded.",
            261: "Stamps the composite value onto every row of this date.",
            262: "Closes the stamping loop.",
            263: "Extends the master accumulator with today's rows.",
            264: "Returns the assembled DataFrame with the canonical schema.",
            265: "ROLLING_ESTIMATORS: the three allowed rolling smoother names.",
            266: "Defines _rolling_agg: applies an unweighted rolling estimator to a Series.",
            267: "",
            268: "Docstring (min_periods=1 so early data still yields a value).",
            269: "",
            270: "",
            271: "mean path: rolling arithmetic mean.",
            272: "",
            273: "",
            274: "Returns it.",
            275: "median path: rolling median.",
            276: "Returns it.",
            277: "trimmed_mean path: builds a small inner trimmer...",
            278: "Coerces the window values to a float array.",
            279: "Drops NaNs.",
            280: "Nothing left: return NaN.",
            281: "Trims with equal weights (this rolling is unweighted).",
            282: "Applies the trimmer with raw=True (numpy in, scalar out).",
            283: "Unknown estimator: raise a ValueError naming the allowed choices.",
            284: "Defines compute_rolling_index: weekly/monthly rollups of daily values.",
            285: "Parameter: the daily-index DataFrame.",
            286: "Parameter: window length — 7 (weekly) or 30 (monthly).",
            287: "",
            288: "Parameter: rounding precision.",
            289: "Parameter: the rolling estimator.",
            290: "",
            291: "",
            292: "Parameter: the trim fraction.",
            293: "Return type: a rolled DataFrame.",
            294: "Docstring (first part).",
            295: "Docstring: anchored at each index_date (min_periods=1 for early data)...",
            296: "...estimator is mean (default), median, or trimmed_mean over the trailing window.",
            297: "Closes the docstring.",
            298: "Empty input: empty frame with the canonical schema.",
            299: "Returns early.",
            300: "",
            301: "Sorts by window, route, then date so each group is time-ordered.",
            302: "Rolling route_price per (window, route)...",
            303: "...applied via a groupby transform...",
            304: "...using the shared _rolling_agg helper.",
            305: "Closes the call.",
            306: "Rolling route_index per (window, route)...",
            307: "",
            308: "...transform...",
            309: "...same helper.",
            310: "Closes the call.",
            311: "Rolling aggregate per window ONLY...",
            312: "...because the composite is one number per date...",
            313: "...transform across the shared series.",
            314: "Closes the call.",
            315: "Opens the output-frame assembly...",
            316: "index_date carried over.",
            317: "lead_window_days carried over.",
            318: "route carried over.",
            319: "weight carried over.",
            320: "route_price = rolled value, rounded.",
            321: "",
            322: "route_index = rolled value, rounded.",
            323: "aggregate_index = rolled composite, rounded.",
            324: "base_period carried over.",
            325: "Closes the dict.",
            326: "Closes the DataFrame constructor.",
            327: "Resets the index and returns.",
            328: "Defines write_index: writes an index DataFrame to a *_index table.",
            329: "Parameter: the index DataFrame.",
            330: "Parameter: the table name.",
            331: "Parameter: the database path (optional).",
            332: "Return type: the number of rows written.",
            333: "Docstring (first part).",
            334: "Docstring: re-running for the same date re-computes rather than duplicating.",
            335: "",
            336: "",
            337: "Closes the docstring.",
            338: "Rejects unknown table names...",
            339: "Raises a clear ValueError.",
            340: "Empty input: nothing to write...",
            341: "",
            342: "...log it...",
            343: "...and return 0 rows.",
            344: "Reorders to the canonical columns before inserting.",
            345: "Opens a connection.",
            346: "",
            347: "try block so it always closes.",
            348: "Loops over each (date, window) group...",
            349: "Deletes existing rows for that exact date and window (opened)...",
            350: "",
            351: "...parameterised DELETE statement...",
            352: "With the day and window as parameters.",
            353: "Closes the execute call.",
            354: "Converts the frame to plain tuples.",
            355: "Bulk-inserts everything.",
            356: "Commits the transaction.",
            357: "Returns the row count.",
            358: "finally: closes the connection.",
            359: "Closes the try/finally block.",
            360: "Batch-inserts all rows for the current table in one executemany call.",
            361: "Commits the transaction so every insert persists.",
            362: "Returns the number of rows written to this table.",
            363: "Guarantees the connection is closed even if an insert raises.",
            364: "Closes the database connection.",
        },
    },
    # ── FILE 16: tests/test_indexer.py ──────────────────────────────────────────
    {
        "out": "22-test-indexer-py.html",
        "src": "tests/test_indexer.py",
        "title": "Walkthrough 22: tests/test_indexer.py",
        "prev": "21-test-scraper-py.html",
        "next": "23-estimators-py.html",
        "notes": {
            0: "Module docstring: the test suite for src.indexer.api_index — the APIx weighted basket index.",
            1: "",
            2: "Docstring: all tests run offline using tests/fixtures/sample_cleaned.csv.",
            3: "Closes the docstring.",
            4: "Imports Path for fixture file resolution.",
            5: "",
            6: "Imports pandas for DataFrame assertions.",
            7: "Imports pytest for test utilities and pytest.approx.",
            8: "Imports yaml — used by the estimator-config end-to-end test.",
            9: "",
            10: "Opens the import block from src.indexer.api_index.",
            11: "CONFIG_PATH — the real indexer.yaml (edited by the config-flag test).",
            12: "INDEX_COLUMNS — for schema verification.",
            13: "compute_daily_index — the 36-cell daily calculator.",
            14: "compute_rolling_index — weekly/monthly rollups.",
            15: "load_estimator_config — the estimator settings under test.",
            16: "load_route_weights — config validation.",
            17: "load_window_weights — window shares config validation.",
            18: "route_price_per_day — the price-collapse function.",
            19: "write_index — the SQLite upsert function.",
            20: "Closes the import block.",
            21: "Imports get_connection and init_db from the storage layer.",
            22: "",
            23: "FIXTURES: path to the tests/fixtures directory.",
            24: "CSV: path to the sample_cleaned.csv test fixture.",
            25: "",
            26: "WEIGHTS: hardcoded test weights for the 3-route fixture.",
            27: "Comment: equal booking-lead-time shares for the 3-route × 2-window fixture...",
            28: "...every cell weight = route weight × 0.5, so the fixture blends both windows 50/50.",
            29: "WINDOW_WEIGHTS: the window shares the tests pass in.",
            30: "",
            31: "",
            32: "pytest fixture marker.",
            33: "cleaned_df: returns the sample CSV as a DataFrame.",
            34: "Reads sample_cleaned.csv.",
            35: "",
            36: "",
            37: "pytest fixture marker.",
            38: "prices: takes cleaned_df as input.",
            39: "Collapses to one fare per (route, window, date) with the default median.",
            40: "",
            41: "",
            42: "pytest fixture marker.",
            43: "daily: takes prices as input.",
            44: "Computes the daily index with the test weights AND window weights.",
            45: "",
            46: "",
            47: "Helper _rows: filters the daily frame by window and date.",
            48: "Boolean mask over the two columns, returned as a fresh frame.",
            49: "",
            50: "",
            51: "Section header: config tests.",
            52: "",
            53: "test_route_weights_load_and_normalise: verifies config loading.",
            54: "Loads the real weights from config/indexer.yaml.",
            55: "There must be 12 directional routes.",
            56: "The weights must sum to 1.0 (within tolerance).",
            57: "DEL-BOM must carry positive weight.",
            58: "",
            59: "",
            60: "test_estimator_config_loads_expected_keys: verifies the estimator settings.",
            61: "Loads the estimator config.",
            62: "The key set must be exactly these five...",
            63: "aggregation_estimator.",
            64: "aggregation_trim_frac.",
            65: "rolling_estimator.",
            66: "rolling_trim_frac.",
            67: "route_price_method.",
            68: "Closes the set literal.",
            69: "Default aggregation estimator is weighted_mean.",
            70: "Default aggregate trim is 10%.",
            71: "Default rolling estimator is mean.",
            72: "Default rolling trim is 10%.",
            73: "Default route-price collapse is median.",
            74: "",
            75: "",
            76: "test_window_weights_load_and_normalise: verifies window shares config.",
            77: "Loads the window weights from config.",
            78: "The three windows 1, 7 and 30 must be present.",
            79: "They must sum to 1.0.",
            80: "The month-ahead share must beat the last-minute share (0.5 vs 0.2).",
            81: "",
            82: "",
            83: "Section header: price-collapse tests.",
            84: "",
            85: "test_price_per_day_excludes_outliers: the flagged row must vanish.",
            86: "The fixture has 30 cleaned rows.",
            87: "Exactly 1 row is flagged as an outlier.",
            88: "Grabs that flagged row.",
            89: "It is on route DEL-BOM.",
            90: "It is in window 7.",
            91: "It was scraped on 2026-09-04.",
            92: "Builds the combo filter for that exact cell...",
            93: "...filter part 1: route match.",
            94: "...filter part 2: window match.",
            95: "...filter part 3: date match.",
            96: "Closes the filter.",
            97: "The cell survived with exactly one price row.",
            98: "Comment: the outlier fare 4200 is excluded; 9/3's price carried forward instead.",
            99: "So the cell price is 4050 (the carried-forward fare), not 4200.",
            100: "",
            101: "",
            102: "test_price_per_day_uses_median_fare_by_default: 3 fares collapse to the middle one.",
            103: "Opens a tiny DataFrame fixture...",
            104: "Three rows on route A-B.",
            105: "All in window 1.",
            106: "All scraped on 2026-09-01.",
            107: "Fares 5000, 4800, 5200.",
            108: "No outliers.",
            109: "Closes the dict.",
            110: "Closes the DataFrame call.",
            111: "Collapses with the default method.",
            112: "The median is 5000, NOT the cheapest 4800.",
            113: "test_price_per_day_uses_min_fare_when_specified: same data, explicit min.",
            114: "",
            115: "",
            116: "Opens the same tiny fixture frame...",
            117: "Three rows on route A-B.",
            118: "Window 1.",
            119: "Same date.",
            120: "Same fares.",
            121: "No outliers.",
            122: "Closes the dict.",
            123: "Closes the DataFrame call.",
            124: "Collapses with method=min.",
            125: "Now the cheapest fare 4800 wins.",
            126: "test_price_per_day_rejects_unknown_method: bad method must raise.",
            127: "Opens a two-row fixture...",
            128: "",
            129: "",
            130: "Two rows.",
            131: "Window 1.",
            132: "Same date.",
            133: "Fares 5000 and 4800.",
            134: "No outliers.",
            135: "Closes the dict.",
            136: "Closes the DataFrame call.",
            137: "Expects a ValueError.",
            138: "Calls with the nonsense method 'avg'.",
            139: "Closes the with block.",
            140: "test_price_per_day_carries_forward_across_gap: missing days are filled.",
            141: "Fixture with a coverage gap on 2026-09-02...",
            142: "",
            143: "",
            144: "Three rows.",
            145: "Window 1.",
            146: "Dates 09-01, 09-03, 09-04 (09-02 missing).",
            147: "Fares 5000, 5200, 5400.",
            148: "No outliers.",
            149: "Closes the dict.",
            150: "Closes the DataFrame call.",
            151: "Collapses the fares.",
            152: "The gap date must now exist...",
            153: "Exactly one row for 09-02.",
            154: "Its price is the last known fare, 5000.",
            155: "test_price_per_day_no_phantom_dates_before_first_observation: no fill before the start.",
            156: "Fixture that only starts on 09-03...",
            157: "Two rows.",
            158: "",
            159: "",
            160: "Window 1.",
            161: "Dates 09-03 and 09-04 only.",
            162: "Fares.",
            163: "No outliers.",
            164: "Closes the dict.",
            165: "Closes the DataFrame call.",
            166: "Collapses.",
            167: "Only the two real dates exist — 09-01/09-02 are NOT invented.",
            168: "Section header: daily-index tests.",
            169: "test_base_day_is_100_for_each_window: the base date anchors at 100.",
            170: "Checks windows 1 and 7.",
            171: "Grabs the base-date rows for this window.",
            172: "",
            173: "",
            174: "The base date must have data.",
            175: "",
            176: "Every route_index equals 100.0.",
            177: "The aggregate headline equals 100.0 too.",
            178: "test_weighted_index_math: verifies the 36-cell composite formula.",
            179: "Comment: day 3, the 36-cell basket (route weight × 0.5 window share each).",
            180: "Comment: t+1 cell indices — DEL-BOM 98.0, DEL-BLR 101.67...",
            181: "...BOM-BLR 105.71.",
            182: "",
            183: "",
            184: "Comment: t+7 cell indices — DEL-BOM 101.25, DEL-BLR 101.0...",
            185: "...BOM-BLR 106.67.",
            186: "Comment: composite = sum of cell_index × route_w × 0.5 = 102.11, ONE headline per date.",
            187: "Grabs day 3, window 1, indexed by route.",
            188: "DEL-BOM route_index ≈ 98.0.",
            189: "DEL-BLR route_index ≈ 101.67.",
            190: "BOM-BLR route_index ≈ 105.71.",
            191: "The composite headline ≈ 102.11.",
            192: "Comment: the composite is identical for every row of the same date.",
            193: "So there is only one distinct headline on day 3 window 1...",
            194: "...and the same for window 7.",
            195: "test_daily_index_aggregate_median_estimator: weighted median over the 6 cells.",
            196: "Comment: day 3, the 6 cell indices sorted with their weights...",
            197: "...cumulative weight crosses 0.5 at 101.25.",
            198: "Rebuilds daily with estimator=weighted_median.",
            199: "",
            200: "",
            201: "Grabs day 3, window 1.",
            202: "The composite headline ≈ 101.25.",
            203: "test_daily_index_aggregate_trimmed_estimator: 10% weight-trim over the 6 cells.",
            204: "Comment: cumulative weights 0.2/0.35/0.55/0.7/0.85/1.0...",
            205: "...kept weights give ≈ 102.05.",
            206: "Rebuilds daily with estimator=weighted_trimmed_mean.",
            207: "",
            208: "",
            209: "Grabs day 3, window 1.",
            210: "The composite headline ≈ 102.05.",
            211: "test_missing_route_carries_forward_last_fare: the outlier day still has data.",
            212: "Comment: window 7, day 4 — DEL-BOM's 9/4 fare is an outlier...",
            213: "...so 9/3's fare (4050) is carried forward; the route is NOT missing...",
            214: "...and the composite ≈ 104.36.",
            215: "",
            216: "",
            217: "Grabs window 7, day 4.",
            218: "Indexes by route.",
            219: "All three routes are present (the row was carried forward, not dropped).",
            220: "DEL-BOM's price is the carried-forward 4050.",
            221: "Its route_index ≈ 101.25.",
            222: "Its composite headline ≈ 104.36.",
            223: "test_cells_without_a_shared_base_join_later_at_100: late-starting cells join cleanly.",
            224: "Comment: a window that starts after the shared base day has no base fare...",
            225: "...it prices itself against its own first observation and joins at 100.",
            226: "Stitches the fixture prices together...",
            227: "",
            228: "",
            229: "...the existing prices...",
            230: "...plus a brand-new window-30 cell...",
            231: "...on route DEL-BOM...",
            232: "...window 30...",
            233: "...starting 2026-09-03...",
            234: "...at price 6000.",
            235: "Closes the inner frame.",
            236: "Closes the dict.",
            237: "Closes the list.",
            238: "...with ignore_index.",
            239: "Closes concat.",
            240: "Builds daily with window weights that include a (still tiny) 30 share.",
            241: "Grabs window 30 on 2026-09-03, indexed by route.",
            242: "It joins at route_index exactly 100.",
            243: "Comment: the cell prices itself against its OWN first observation...",
            244: "...while cells on the shared base keep the global anchor.",
            245: "base_period is the cell's own first date, 2026-09-03.",
            246: "Window-1 cells on the same day still anchor to 2026-09-01.",
            247: "Window 30's first index_date is 2026-09-03.",
            248: "Comment: joining at 100 means the composite does not jerk upward on day one.",
            249: "So the headline on the join day equals the first window-30 headline.",
            250: "test_never_observed_route_stays_omitted: zero-weight routes never appear.",
            251: "Weights include a phantom GHOST-RTE at weight 0.",
            252: "Computes the daily index.",
            253: "GHOST-RTE is not in the output routes.",
            254: "test_route_price_in_daily: prices propagate into the daily table.",
            255: "Grabs day 2, window 1, indexed by route.",
            256: "",
            257: "",
            258: "DEL-BLR's price is 6000.",
            259: "BOM-BLR's price is 3600.",
            260: "test_empty_prices_gives_empty: empty input yields empty output.",
            261: "Builds an empty prices frame.",
            262: "",
            263: "",
            264: "compute_daily_index returns empty.",
            265: "compute_rolling_index on an empty daily also returns empty.",
            266: "Section header: rolling (weekly/monthly) tests.",
            267: "test_rolling_route_index: rolling mean of route indices.",
            268: "",
            269: "",
            270: "Rebuilds prices from the CSV fixture.",
            271: "Rebuilds the daily index.",
            272: "Rolls a 3-day window (short enough for the 5-day fixture).",
            273: "Filters window 1 and indexes by (date, route).",
            274: "",
            275: "",
            276: "Comment: DEL-BOM route_index 100, 104, 98, 106, 102 → 3-day mean at d3 = 100.67.",
            277: "",
            278: "Day 3 has ≈ 100.67.",
            279: "Comment: day 1 with min_periods=1 equals the daily value.",
            280: "Day 1 is ≈ 100.0.",
            281: "test_rolling_route_index_median_estimator: rolling median.",
            282: "Rebuilds prices.",
            283: "Rebuilds daily.",
            284: "Rolls with estimator=median.",
            285: "Filters window 1, indexes by route.",
            286: "Comment: median(100, 104) = 102 at d2.",
            287: "",
            288: "",
            289: "Day 2 ≈ 102.0.",
            290: "Comment: median(100, 104, 98) = 100 at d3.",
            291: "Day 3 ≈ 100.0.",
            292: "test_rolling_route_index_trimmed_estimator: rolling weight-trimmed mean.",
            293: "Rebuilds prices.",
            294: "Rebuilds daily.",
            295: "Rolls with estimator=trimmed_mean, trim_frac=0.10.",
            296: "Filters window 1, indexes by route.",
            297: "Comment: 10% trim over [98, 100, 104] → ≈ 100.58.",
            298: "",
            299: "",
            300: "Day 3 ≈ 100.58.",
            301: "test_weekly_aggregate_is_rolling_mean_of_daily_aggregate: weekly = mean of daily headlines.",
            302: "Rebuilds prices.",
            303: "Rebuilds daily.",
            304: "Rolls a 7-day window (covers the whole fixture here).",
            305: "Unique daily headlines for window 1.",
            306: "Their mean is the expected weekly value.",
            307: "",
            308: "",
            309: "Weekly window-1 rows.",
            310: "The last weekly headline.",
            311: "It must equal the mean of the daily headlines.",
            312: "test_rolling_writes_all_index_columns: the output schema is canonical.",
            313: "Rebuilds prices.",
            314: "Rebuilds daily.",
            315: "Rolls weekly.",
            316: "The column list exactly matches INDEX_COLUMNS.",
            317: "And the output is non-empty.",
            318: "",
            319: "",
            320: "Section header: write / idempotency tests.",
            321: "test_write_index_overwrites_same_date: re-running must not duplicate.",
            322: "A temp database file.",
            323: "Creates the schema.",
            324: "Rebuilds prices from the CSV.",
            325: "Rebuilds daily.",
            326: "",
            327: "",
            328: "First write.",
            329: "",
            330: "Second write of the same values.",
            331: "Opens the database to verify.",
            332: "try block.",
            333: "Total row count in daily_index.",
            334: "Opens the specific date-window query...",
            335: "",
            336: "...SELECT with 2026-09-01 / window 1 filter...",
            337: "Fetches the count.",
            338: "",
            339: "finally: close the connection.",
            340: "Closes the block.",
            341: "Both writes returned the same count as the final total (no duplication).",
            342: "Exactly 3 rows for that date-window → 3 routes, no duplicates.",
            343: "test_write_index_rejects_unknown_table: unknown table names are refused.",
            344: "An empty frame with the canonical schema.",
            345: "Expects a ValueError.",
            346: "Tries writing to 'hack_index'.",
            347: "",
            348: "Section header: end-to-end integration tests.",
            349: "test_run_index_end_to_end: the full pipeline on a temp database.",
            350: "",
            351: "",
            352: "Imports run_index locally to keep the test suite import-light.",
            353: "Temp database path.",
            354: "Creates the schema.",
            355: "Loads the CSV fixture.",
            356: "",
            357: "",
            358: "Opens a connection.",
            359: "",
            360: "try block.",
            361: "Writes cleaned_flights into it.",
            362: "",
            363: "finally: close.",
            364: "Closes the block.",
            365: "Runs the whole pipeline against the temp db.",
            366: "Comment: 5 dates × 2 windows × 3 routes; carry-forward fills the one gap.",
            367: "Expected daily rows = 30.",
            368: "Daily count matches.",
            369: "Weekly count matches.",
            370: "Monthly count matches.",
            371: "",
            372: "Opens the database to verify results.",
            373: "",
            374: "try block.",
            375: "Pulls the distinct (aggregate, window, date) triples.",
            376: "finally: close.",
            377: "Closes the block.",
            378: "daily_index must be populated.",
            379: "",
            380: "test_run_index_respects_estimator_config: a custom config file is honoured.",
            381: "Imports run_index locally.",
            382: "Temp database.",
            383: "Creates the schema.",
            384: "Loads the fixture.",
            385: "Opens a connection.",
            386: "",
            387: "",
            388: "try block.",
            389: "Writes cleaned_flights.",
            390: "",
            391: "finally: close.",
            392: "Closes the block.",
            393: "A temp config file path.",
            394: "Loads the REAL indexer.yaml as a dict.",
            395: "Switches the aggregation estimator to weighted_median.",
            396: "Switches the rolling estimator to median.",
            397: "Writes the modified config out.",
            398: "Runs the pipeline with the custom config.",
            399: "",
            400: "Still builds 30 daily rows.",
            401: "Opens the db to verify.",
            402: "try block.",
            403: "Reads one aggregate value...",
            404: "...for 2026-09-03, window 1...",
            405: "",
            406: "Closes the SELECT.",
            407: "Fetches the row.",
            408: "",
            409: "Counts weekly rows for window 1...",
            410: "...fetches the count.",
            411: "finally: close.",
            412: "Closes the block.",
            413: "Comment: day 3, weighted median over the 6 fixture cells with config window weights...",
            414: "...cum 0.08/0.17/0.29/0.35/0.41/0.50 crosses the weight half at 101.25.",
            415: "The stored headline ≈ 101.25.",
            416: "Weekly has 15 rows (3 routes × 5 dates) — rolling median ran fine.",
            417: "Fetches the daily index value computed for that date.",
            418: "Runs the cleanup clause regardless of whether the assertions passed.",
            419: "Closes the database connection.",
            420: "",
            421: "Comment: explains the expected weighted-median value for Day 3.",
            422: "Comment: notes the window weights in play; window 30 is absent from the fixture data.",
            423: "Comment: walks the cumulative share to the 0.25 crossing at 101.25.",
            424: "Asserts the day-3 aggregate equals the hand-computed 101.25 (within 0.01).",
            425: "Asserts 15 rows surfaced for the 3-route x 5-date weekly index.",
        },
    },
    # ── FILE 17: src/indexer/estimators.py ──────────────────────────────────────
    {
        "out": "23-estimators-py.html",
        "src": "src/indexer/estimators.py",
        "title": "Walkthrough 23: src/indexer/estimators.py",
        "prev": "22-test-indexer-py.html",
        "next": "24-synthetic-py.html",
        "notes": {
            0: "Module docstring: the robust aggregation estimators behind the APIx headline.",
            1: "",
            2: "Docstring: three ways to combine route indices (and their weights)...",
            3: "...into a single daily headline, selected by name in config/indexer.yaml.",
            4: "",
            5: "weighted_mean — the classic Laspeyres behaviour: sum(v·w) / sum(w).",
            6: "weighted_trimmed_mean — shave trim_frac of weight from each tail...",
            7: "...then re-balance and average the survivors.",
            8: "weighted_median — the value at which cumulative weight crosses 0.5.",
            9: "",
            10: "Docstring: trimming is measured in WEIGHT MASS, not route count...",
            11: "...cheap/costly extremes are removed until the desired share is set aside...",
            12: "...so a small route is fully eaten while a big route is only partially shaved.",
            13: "",
            14: "Docstring: all functions take parallel values/weights array-likes and return a float...",
            15: "...a single surviving value (or NaN for degenerate input) is returned as-is.",
            16: "Closes the docstring.",
            17: "Enables forward type annotations.",
            18: "",
            19: "Typing: Callable for the registry, Sequence for inputs.",
            20: "",
            21: "Imports numpy for all array arithmetic.",
            22: "",
            23: "DEFAULT_TRIM_FRAC: the 10% default trim used everywhere.",
            24: "",
            25: "",
            26: "Defines _as_arrays: validates and converts inputs to aligned float arrays.",
            27: "Docstring.",
            28: "Converts values to a float array.",
            29: "Converts weights to a float array.",
            30: "Both must be 1-D...",
            31: "...else raise a clear error.",
            32: "Both must have the same length...",
            33: "...else raise.",
            34: "Returns the two aligned arrays.",
            35: "",
            36: "",
            37: "Defines weighted_mean: the classic Laspeyres weighted average.",
            38: "Docstring.",
            39: "Validates and aligns the inputs.",
            40: "Total weight.",
            41: "Non-positive total means nothing to weight...",
            42: "...so return NaN.",
            43: "Σ(v·w) / Σw.",
            44: "",
            45: "",
            46: "Defines weighted_trimmed_mean: weight-trimmed mean.",
            47: "Parameter: values.",
            48: "Parameter: weights.",
            49: "Parameter: trim fraction (defaults to DEFAULT_TRIM_FRAC).",
            50: "Return type.",
            51: "Docstring (first part).",
            52: "",
            53: "Docstring: values are sorted ascending; each element's weight is clipped...",
            54: "...so the cumulative weight stays inside [trim_frac·total, (1-trim_frac)·total].",
            55: "Docstring: returns NaN if nothing survives the trim (trim_frac >= 0.5).",
            56: "Closes the docstring.",
            57: "Validates and aligns the inputs.",
            58: "Total weight.",
            59: "Non-positive total: NaN.",
            60: "Returns NaN.",
            61: "Single value passes through unchanged.",
            62: "Returns it.",
            63: "",
            64: "Sorts values ascending.",
            65: "Reorders v...",
            66: "...and w to match.",
            67: "",
            68: "trim_frac None falls back to the default.",
            69: "Resets trim_frac to DEFAULT_TRIM_FRAC.",
            70: "Clamps trim_frac into [0.0, 0.5].",
            71: "Lower weight boundary.",
            72: "Upper weight boundary.",
            73: "",
            74: "Cumulative weight array.",
            75: "Comment: overlap of each element's weight interval [cum-w, cum] with [lower, upper].",
            76: "Per-element surviving weight after the trim.",
            77: "Total surviving weight.",
            78: "Nothing survived...",
            79: "...fall back to the weighted median.",
            80: "Weighted average of the surviving values.",
            81: "",
            82: "",
            83: "Defines weighted_median: the weighted median of values.",
            84: "Docstring (first line).",
            85: "",
            86: "Docstring: returns the value at which cumulative weight reaches 0.5·total...",
            87: "...when the halfway point falls exactly on a boundary, averages the two neighbours.",
            88: "Closes the docstring.",
            89: "Validates and aligns the inputs.",
            90: "Total weight.",
            91: "Non-positive total: NaN.",
            92: "Returns NaN.",
            93: "Single value passes through.",
            94: "Returns it.",
            95: "",
            96: "Sorts values ascending.",
            97: "Reorders v...",
            98: "...and w.",
            99: "",
            100: "Half the total weight.",
            101: "Cumulative weight array.",
            102: "Finds the index where cumulative weight first exceeds half.",
            103: "Index 0...",
            104: "...return the smallest value.",
            105: "Index past the end...",
            106: "...return the largest value.",
            107: "Comment: exact boundary — cumulative weight equals half → average the neighbours.",
            108: "The boundary case...",
            109: "...returns the midpoint of the two neighbours.",
            110: "Otherwise return the value at idx.",
            111: "",
            112: "",
            113: "ESTIMATORS: the name-to-function registry used by aggregate.",
            114: "Registers weighted_mean.",
            115: "Registers weighted_trimmed_mean.",
            116: "Registers weighted_median.",
            117: "Closes the registry dict.",
            118: "",
            119: "",
            120: "Defines aggregate: dispatches to the named estimator with a uniform signature.",
            121: "Parameter: values.",
            122: "Parameter: weights.",
            123: "Parameter: estimator name.",
            124: "Parameter: trim fraction.",
            125: "Return type.",
            126: "Docstring.",
            127: "Unknown estimator name...",
            128: "...raise...",
            129: "...a ValueError listing the choices.",
            130: "Closes the raise call.",
            131: "weighted_trimmed_mean needs the trim fraction...",
            132: "...pass it through explicitly.",
            133: "All other estimators dispatch directly.",
        },
    },
    # ── FILE 18: src/indexer/synthetic.py ───────────────────────────────────────
    {
        "out": "24-synthetic-py.html",
        "src": "src/indexer/synthetic.py",
        "title": "Walkthrough 24: src/indexer/synthetic.py",
        "prev": "23-estimators-py.html",
        "next": "25-metrics-py.html",
        "notes": {
            0: "Module docstring: a deterministic synthetic cleaned-flights generator for estimator research.",
            1: "",
            2: "Docstring: produces a realistic multi-route multi-window scrape...",
            3: "...with an upward price drift, weekly seasonality (weekends cost more)...",
            4: "...small route-level wobble, occasional sharp spikes...",
            5: "...and deliberate coverage gaps so carry-forward gets exercised.",
            6: "",
            7: "Docstring: output uses the cleaned_flights column schema.",
            8: "Docstring: seeded, so re-running yields identical data...",
            9: "...making the mean-vs-trimmed-vs-median comparison reproducible.",
            10: "Closes the module docstring.",
            11: "",
            12: "Enables forward type annotations.",
            13: "Imports random for the seeded generator.",
            14: "Imports date and timedelta for date arithmetic.",
            15: "",
            16: "Imports Sequence for the windows parameter.",
            17: "",
            18: "Imports pandas for DataFrame construction.",
            19: "ROUTES: the 12 directional city-pair routes (opened).",
            20: "First six routes — Delhi outbound and return legs.",
            21: "Second six routes — the rest of the city pairs.",
            22: "",
            23: "Closes the ROUTES list.",
            24: "BASE_PRICES: a realistic base fare per route (opened).",
            25: "DEL routes ~5100-5200, BLR routes ~4500-4600.",
            26: "MAA and BOM routes ~4300-4800.",
            27: "MAA-BLR routes ~3800-3900.",
            28: "",
            29: "Closes the BASE_PRICES dict.",
            30: "",
            31: "",
            32: "WINDOWS: the three booking lead windows to generate.",
            33: "Defines _base_date: the anchor date of the synthetic period.",
            34: "",
            35: "",
            36: "August 1st, 2026 — the shared base for every series.",
            37: "Defines make_synthetic_cleaned: the public seeded generator.",
            38: "Parameter: the random seed (default 7).",
            39: "Parameter: number of days per route+window (default 15).",
            40: "Parameter: the lead windows to simulate.",
            41: "Parameter: probability of a sharp fare spike (default 3%).",
            42: "Return type: a cleaned_flights-shaped DataFrame.",
            43: "",
            44: "Docstring (first line).",
            45: "Docstring: price model per (route, window, day).",
            46: "Docstring: drift (slow rise) × weekend bump × small wobble.",
            47: "Docstring: plus a chance of a sharp spike (promo/fare glitch)...",
            48: "...and one deliberate coverage gap day per route+window.",
            49: "Closes the docstring.",
            50: "Seeded random generator — reproducible output.",
            51: "The anchor date for all series.",
            52: "",
            53: "Row accumulator.",
            54: "Loops over each lead window.",
            55: "Loops over the routes, with an offset per route.",
            56: "Comment: coverage gap mid-series (never day 0, never the last day)...",
            57: "...so the route is never orphaned from its base period.",
            58: "The gap day for this route, cycled so it stays inside the window.",
            59: "Loops over each day in the window.",
            60: "Comment: deliberate coverage gap — one missing day per route+window.",
            61: "This is the gap day...",
            62: "",
            63: "...skip it.",
            64: "Splits the shifted date into year, month, day components.",
            65: "",
            66: "Formats the date as YYYY-MM-DD.",
            67: "The route's base price.",
            68: "Slow upward drift over time.",
            69: "Weekend bump: 8% higher on Friday/Saturday.",
            70: "Small random wobble around the trend.",
            71: "Combines all four components into the fare.",
            72: "Random chance of a spike...",
            73: "",
            74: "...multiplies the fare by 1.6.",
            75: "Opens the row dict...",
            76: "scrape_date.",
            77: "route.",
            78: "origin — first half of the route code.",
            79: "dest — second half of the route code.",
            80: "carrier — a fixed synthetic carrier.",
            81: "flight_no — synthetic flight number.",
            82: "depart_time — a fixed 08:00 departure.",
            83: "arrive_time — a fixed 10:30 arrival.",
            84: "duration_mins — fixed 150 minutes.",
            85: "stops — always 0 for synthetic rows.",
            86: "base_fare — 85% of the total fare.",
            87: "taxes — the remaining 15%.",
            88: "total_fare — the combined fare, rounded.",
            89: "currency — INR.",
            90: "lead_window_days — the current window.",
            91: "scrape_timestamp — 06:00 on the same day.",
            92: "quality_score — always perfect (1.0).",
            93: "is_outlier — never flagged.",
            94: "dedup_hash — a stable synthetic key.",
            95: "Closes the row dict.",
            96: "Appends it to the rows.",
            97: "",
            98: "Builds the DataFrame from all generated rows.",
            99: "",
            100: "",
            101: "Defines _add_days: adds n days to a base date.",
            102: "Returns the shifted date via timedelta.",
        },
    },
    # ── FILE 19: src/indexer/metrics.py ─────────────────────────────────────────
    {
        "out": "25-metrics-py.html",
        "src": "src/indexer/metrics.py",
        "title": "Walkthrough 25: src/indexer/metrics.py",
        "prev": "24-synthetic-py.html",
        "next": "26-report-py.html",
        "notes": {
            0: "Module docstring: stability metrics for picking the most robust headline estimator.",
            1: "",
            2: "Docstring: given the same price data, re-run the index under several estimators...",
            3: "...and score how stable each daily headline is:",
            4: "",
            5: "mean_abs_change — average index-point move day-to-day (lower = calmer).",
            6: "std_change — volatility sigma of those moves (lower = calmer).",
            7: "max_abs_change — worst single-day move (lower = calmer).",
            8: "extreme_move_days — count of days with |move| over a threshold (lower = calmer).",
            9: "",
            10: "Docstring: stable is not the same as smooth-for-its-own-sake — the report also prints...",
            11: "...a route-sensitivity table so we can see whether stability comes from ignoring...",
            12: "...a genuinely informative route rather than just trimming noise.",
            13: "Closes the docstring.",
            14: "Enables forward type annotations.",
            15: "",
            16: "Imports Sequence for the estimator list parameter.",
            17: "",
            18: "Imports numpy for the stability math.",
            19: "Imports pandas for the DataFrame work.",
            20: "",
            21: "Imports compute_daily_index from the index builder.",
            22: "",
            23: "DEFAULT_THRESHOLD: the default extreme-move cutoff of 5 index points.",
            24: "",
            25: "AGGREGATION_ESTIMATORS: the three estimators the comparison runs.",
            26: "",
            27: "STABILITY_COLUMNS: the four stability metrics (opened).",
            28: "mean_abs_change.",
            29: "std_change.",
            30: "max_abs_change.",
            31: "extreme_move_days.",
            32: "Closes the tuple.",
            33: "",
            34: "",
            35: "Defines stability_stats: point-change stability statistics for a daily series.",
            36: "Docstring.",
            37: "Converts the values to a float array.",
            38: "Drops NaN values.",
            39: "Day-to-day differences.",
            40: "No differences at all (zero or one value)...",
            41: "Return a dict...",
            42: "...mean_abs_change is NaN.",
            43: "...std_change is NaN.",
            44: "...max_abs_change is NaN.",
            45: "...and extreme_move_days is 0.",
            46: "Closes the empty diff dict.",
            47: "Otherwise build the stats dict:",
            48: "mean absolute change.",
            49: "sample standard deviation of the changes (NaN for a single diff).",
            50: "maximum absolute change.",
            51: "number of moves exceeding the threshold.",
            52: "Closes the stats dict.",
            53: "",
            54: "",
            55: "Defines aggregate_by_day: the unique daily aggregate series for one window.",
            56: "Docstring.",
            57: "Opens the filter...",
            58: "...keeps rows for this window with a non-null aggregate...",
            59: "Closes the filter.",
            60: "Opens the series pipeline...",
            61: "...drop duplicate dates...",
            62: "...index by date and take the aggregate column...",
            63: "...sorted by date.",
            64: "Closes the pipeline.",
            65: "",
            66: "",
            67: "Defines compare_aggregation_estimators: per-estimator × window stability table.",
            68: "Parameter: the prices DataFrame.",
            69: "Parameter: the route weights.",
            70: "Parameter: the estimators to compare (default all three).",
            71: "Parameter: the trim fraction.",
            72: "Parameter: the windows to score (None means all present).",
            73: "Parameter: optional window weights.",
            74: "Return type: mapping of estimator name to a DataFrame.",
            75: "Docstring (first part).",
            76: "",
            77: "Docstring: returns estimator → DataFrame, one row per window with the four metrics.",
            78: "Docstring: one composite headline per date, so every window row shows the same...",
            79: "...composite stability...",
            80: "...the window dimension is kept for reporting compatibility.",
            81: "Closes the docstring.",
            82: "Windows to use: the given list, or every unique window in the data.",
            83: "Result accumulator.",
            84: "Loops over the estimators...",
            85: "...build the daily index with that estimator...",
            86: "...with 4-decimal rounding and the trim fraction.",
            87: "Closes the daily call.",
            88: "Per-window row storage.",
            89: "Loops over the active windows...",
            90: "...extract the daily aggregate series...",
            91: "...and score it.",
            92: "Builds a transposed frame: windows as rows.",
            93: "Labels the row index as lead_window_days.",
            94: "Returns the per-estimator map.",
            95: "",
            96: "",
            97: "Defines route_sensitivity: headline move when each route loses all data.",
            98: "Parameter: the prices DataFrame.",
            99: "Parameter: the route weights.",
            100: "Parameter: the estimator.",
            101: "Parameter: the trim fraction.",
            102: "Parameter: which window to score.",
            103: "Parameter: optional window weights.",
            104: "Return type: a Series of sensitivity scores, sorted descending.",
            105: "Docstring (first part): mean |headline move| when a route loses all data.",
            106: "",
            107: "Docstring: the estimator re-normalises and missing fares carry forward...",
            108: "...so losing one route moves the headline very little...",
            109: "...SMALLER is better — a robustness stat, not a weight stat.",
            110: "Closes the docstring.",
            111: "Opens the full-index build...",
            112: "...with all routes present.",
            113: "Closes the call.",
            114: "The baseline daily aggregate series.",
            115: "",
            116: "Sensitivity accumulator.",
            117: "Loops over every route...",
            118: "...weights with this route removed...",
            119: "Opens the reduced-index build...",
            120: "...without the route...",
            121: "...same estimator and trim.",
            122: "Closes the call.",
            123: "The abridged daily series.",
            124: "Joins base and abridged, forward-filling gaps.",
            125: "Mean absolute difference between the two series.",
            126: "Closes the route loop; returns the Series sorted big-to-small.",
            127: "",
            128: "",
            129: "Defines weight_elasticity: headline move when each route's weight is bumped.",
            130: "Parameter: the prices DataFrame.",
            131: "Parameter: the route weights.",
            132: "Parameter: the estimator.",
            133: "Parameter: the trim fraction.",
            134: "Parameter: the window to score.",
            135: "Parameter: how much to bump the weight (default 0.01).",
            136: "Parameter: optional window weights.",
            137: "Return type: a Series of leverage scores, sorted descending.",
            138: "Docstring (first part): mean |headline move| when one route's weight is bumped by delta.",
            139: "",
            140: "Docstring: each route's weight is increased by delta and the whole vector...",
            141: "...re-normalised so everything else scales down...",
            142: "Docstring: routes whose DGCA traffic-share estimate is decoupled from price behaviour...",
            143: "...stand out — these are the weights that need attention.",
            144: "Closes the docstring.",
            145: "Opens the full-index build...",
            146: "...with the original weights.",
            147: "Closes the call.",
            148: "The baseline daily aggregate.",
            149: "Total weight of the original vector.",
            150: "",
            151: "Leverage accumulator.",
            152: "Loops over every route...",
            153: "...copy the weights dict...",
            154: "...bump this route's weight by delta...",
            155: "...and re-normalise the whole vector...",
            156: "Opens the moved-index build...",
            157: "...with the renormalised weights...",
            158: "...same estimator and trim.",
            159: "Closes the call.",
            160: "The shifted daily series.",
            161: "Joins base and shifted, forward-filling gaps.",
            162: "Mean absolute difference between the two series.",
            163: "Closes the route loop; returns the leverage Series sorted big-to-small.",
            164: "",
            165: "",
            166: "Defines best_estimator_per_window: window → calmest estimator.",
            167: "Parameter: the comparison map from compare_aggregation_estimators.",
            168: "Return type: window → estimator name.",
            169: "Docstring: picks the estimator with the lowest mean_abs_change.",
            170: "Accumulator: window → (value, estimator name).",
            171: "Loops over the estimator tables...",
            172: "...and each window row...",
            173: "...read the mean_abs_change...",
            174: "...skip NaN values...",
            175: "Continues.",
            176: "Keeps the estimator only if it beats the current best...",
            177: "...storing (value, name).",
            178: "Returns the sorted window → name mapping.",
        },
    },
    # ── FILE 20: src/indexer/report.py ──────────────────────────────────────────
    {
        "out": "26-report-py.html",
        "src": "src/indexer/report.py",
        "title": "Walkthrough 26: src/indexer/report.py",
        "prev": "25-metrics-py.html",
        "next": "27-test-estimators-py.html",
        "notes": {
            0: "Module docstring: runs the estimator stability comparison and prints a plain-text report.",
            1: "",
            2: "Docstring: usage section.",
            3: "Usage: real db, falls back to synthetic data.",
            4: "Usage: point at a specific database.",
            5: "Usage: force synthetic data.",
            6: "",
            7: "Docstring: the report answers the mentor's question about the more stable estimator...",
            8: "Report item 1: aggregation estimator comparison (weighted mean / trimmed / median).",
            9: "Report item 2: rolling estimator comparison (mean / trimmed / median, weekly).",
            10: "Report item 3: route sensitivity (which routes lever the headline).",
            11: "Closes the module docstring.",
            12: "Imports argparse for the CLI flags.",
            13: "Imports logging for status messages.",
            14: "Imports sys for the stdout logging stream.",
            15: "Imports Path for database paths.",
            16: "",
            17: "Imports pandas for DataFrame display.",
            18: "",
            19: "Opens the api_index import block...",
            20: "compute_daily_index and compute_rolling_index.",
            21: "continue: load_estimator_config.",
            22: "load_route_weights and load_window_weights.",
            23: "read_cleaned_flights.",
            24: "route_price_per_day.",
            25: "Closes the api_index import block.",
            26: "Opens the metrics import block...",
            27: "AGGREGATION_ESTIMATORS, STABILITY_COLUMNS, aggregate_by_day.",
            28: "best_estimator_per_window, compare_aggregation_estimators.",
            29: "route_sensitivity, stability_stats, weight_elasticity.",
            30: "Closes the metrics import block.",
            31: "Imports make_synthetic_cleaned from synthetic.",
            32: "Creates the module-level logger.",
            33: "MIN_ROUTES: minimum routes before the real data is used.",
            34: "MIN_DATES: minimum dates before the real data is used.",
            35: "Defines _setup_logging: quiet logging for the report.",
            36: "Calls logging.basicConfig...",
            37: "...with WARNING level (only warnings show)...",
            38: "...a short format...",
            39: "",
            40: "...to stdout.",
            41: "",
            42: "Closes basicConfig.",
            43: "Defines _load_cleaned: returns (cleaned, source_label); falls back to synthetic.",
            44: "",
            45: "",
            46: "Docstring.",
            47: "Skip synthetic when force_synthetic is False...",
            48: "...load the real cleaned table...",
            49: "Opens the adequacy check...",
            50: "...not empty...",
            51: "...enough distinct routes...",
            52: "",
            53: "",
            54: "...and enough distinct dates...",
            55: "Closes the condition.",
            56: "Good enough — return the real data labelled REAL.",
            57: "Otherwise fall back to seeded synthetic data labelled SYNTHETIC.",
            58: "Defines _print_stability_table: prints a labelled, rounded table.",
            59: "Prints a header line.",
            60: "Prints a separator of matching length.",
            61: "Keeps only the stability columns that exist (fallback: all).",
            62: "Prints the table rounded to 3 decimals.",
            63: "Defines _rolling_comparison: 7-day rolling estimator comparison table.",
            64: "Row accumulator.",
            65: "",
            66: "",
            67: "Loops over the windows...",
            68: "...and over the three rolling estimators...",
            69: "...build the 7-day rolling index with that estimator...",
            70: "...extract the aggregate series...",
            71: "...a per-estimator column prefix...",
            72: "",
            73: "",
            74: "...score the series stability...",
            75: "...get (or create) this window's row...",
            76: "...and store each metric under prefix.column...",
            77: "Closes the column loop.",
            78: "Returns the transposed frame, rows labelled by window, rounded.",
            79: "Defines run_report: the main report driver.",
            80: "Loads cleaned data (real or synthetic).",
            81: "Prints the data-source summary (opened)...",
            82: "...row count, route count, and date count.",
            83: "Closes the print.",
            84: "Loads the route weights.",
            85: "Loads the window weights.",
            86: "",
            87: "",
            88: "Loads the estimator settings.",
            89: "Collapses cleaned rows to cell prices.",
            90: "The windows actually present in the data.",
            91: "Prints the window weights.",
            92: "",
            93: "Prints the route price method.",
            94: "Prints the lead windows present.",
            95: "Comment: section 1 — aggregation estimator comparison (daily composite headline).",
            96: "Opens the comparison call...",
            97: "...prices, weights, all three estimators...",
            98: "...the configured trim, the windows, and the window weights.",
            99: "Closes the call.",
            100: "Prints a table per estimator.",
            101: "",
            102: "Closes the table loop.",
            103: "Finds the calmest estimator per window.",
            104: "Prints it.",
            105: "Notes that one headline per date makes every window row the same series.",
            106: "Comment: section 2 — rolling estimator comparison (7-day composite headline).",
            107: "Opens the daily build...",
            108: "...with 4-decimal rounding...",
            109: "...the configured aggregation estimator and trim.",
            110: "Closes the call.",
            111: "Prints the rolling comparison table.",
            112: "",
            113: "Comment: section 3 — route sensitivity + weight elasticity.",
            114: "Opens the route sensitivity call...",
            115: "...with the configured estimator, trim, and window weights.",
            116: "Closes the call.",
            117: "Prints the data-loss robustness header.",
            118: "Prints a separator.",
            119: "",
            120: "Prints the rounded sensitivity table.",
            121: "Opens the weight elasticity call...",
            122: "...with the configured estimator, trim, and window weights.",
            123: "Closes the call.",
            124: "Prints the weight leverage header.",
            125: "Prints a separator.",
            126: "Prints the rounded elasticity table.",
            127: "",
            128: "Defines main: the CLI entry point.",
            129: "Creates the argument parser.",
            130: "Adds --db (optional database path).",
            131: "Adds --synthetic (force synthetic data).",
            132: "Parses the arguments.",
            133: "Configures logging.",
            134: "",
            135: "",
            136: "Runs the report, honouring the flags.",
            137: "Runs main only when executed directly.",
            138: "Calls main.",
            139: "Adds the --synthetic flag to force synthetic data over the real database.",
            140: "Parses the command-line arguments.",
            141: "Configures logging before the report runs.",
            142: "Runs the report, honouring the --synthetic override.",
            143: "",
            144: "",
            145: "Runs main only when this module is executed directly.",
            146: "Calls main.",
        },
    },
    # ── FILE 21: tests/test_estimators.py ───────────────────────────────────────
    {
        "out": "27-test-estimators-py.html",
        "src": "tests/test_estimators.py",
        "title": "Walkthrough 27: tests/test_estimators.py",
        "prev": "26-report-py.html",
        "next": "28-test-metrics-py.html",
        "notes": {
            0: "Module docstring: tests for src.indexer.estimators — the pluggable aggregation estimators.",
            1: "",
            2: "Docstring: all cases use small hand-computed arrays...",
            3: "...so failures are easy to eyeball.",
            4: "Closes the docstring.",
            5: "Imports math for the isnan checks.",
            6: "",
            7: "Imports pytest for assertions and approx.",
            8: "",
            9: "Opens the estimators import block...",
            10: "DEFAULT_TRIM_FRAC and ESTIMATORS.",
            11: "aggregate and weighted_mean.",
            12: "weighted_median.",
            13: "weighted_trimmed_mean.",
            14: "Closes the import block.",
            15: "Comment: the 4-route day from the design discussion.",
            16: "Comment: A=95 (0.40), B=100 (0.30), C=130 (0.20), D=240 (0.10).",
            17: "",
            18: "VALUES: the four route indices.",
            19: "WEIGHTS: the matching weights.",
            20: "test_weighted_mean_matches_laspeyres: checks the classic mean.",
            21: "The weighted mean of the example is 118.0.",
            22: "",
            23: "",
            24: "test_weighted_trimmed_mean_example: checks a hand-computed trim.",
            25: "Comment: 10% weight trimmed off each tail: D removed entirely, A shaved to 0.30.",
            26: "",
            27: "",
            28: "The trimmed mean is 105.625.",
            29: "test_weighted_median_example: checks the weighted median.",
            30: "Comment: cumulative weight at 95=0.40, 100=0.70 → crosses 0.5 at 100.",
            31: "",
            32: "",
            33: "The median is 100.0.",
            34: "test_trim_frac_zero_equals_weighted_mean: trim 0 means the plain mean.",
            35: "Trimming nothing equals the weighted mean of 118.0.",
            36: "",
            37: "",
            38: "test_equal_weight_ten_percent_trim: equal weights, partial trim.",
            39: "Four equal weights of 0.25.",
            40: "",
            41: "",
            42: "Comment: only 0.10 of weight is shaved per end...",
            43: "...so remaining weights 0.15, 0.25, 0.25, 0.15 → mean 134.6875.",
            44: "Asserts the computed trimmed mean...",
            45: "...equals 134.6875.",
            46: "Closes the assert call.",
            47: "test_small_route_fully_removed_by_trim: a tiny route is eaten whole.",
            48: "Comment: a 0.06-weight route at the extreme is eaten entirely by a 0.10 trim.",
            49: "",
            50: "",
            51: "Comment: effective trimmed weights 95→0.27, 100→0.38, 130→0.15, 240→0.00.",
            52: "Comment: mean = 103.9375.",
            53: "The values array.",
            54: "The weights array.",
            55: "Asserts the trimmed mean is 103.9375.",
            56: "test_single_value_passes_through: one value is returned unchanged.",
            57: "weighted_mean of a single value.",
            58: "",
            59: "",
            60: "weighted_trimmed_mean of a single value.",
            61: "weighted_median of a single value.",
            62: "test_all_zero_weights_gives_nan: zero total weight is degenerate.",
            63: "weighted_mean returns NaN.",
            64: "",
            65: "",
            66: "weighted_trimmed_mean returns NaN.",
            67: "weighted_median returns NaN.",
            68: "test_empty_input_gives_nan: empty arrays are degenerate too.",
            69: "weighted_mean returns NaN.",
            70: "",
            71: "",
            72: "weighted_trimmed_mean returns NaN.",
            73: "weighted_median returns NaN.",
            74: "test_length_mismatch_raises: lengths must match.",
            75: "weighted_mean raises.",
            76: "",
            77: "",
            78: "Closes the with block.",
            79: "weighted_trimmed_mean raises.",
            80: "Closes the with block.",
            81: "test_median_exact_boundary_averages_neighbours: boundary case averages.",
            82: "Comment: cumulative weight hits 0.5 exactly at the boundary → midpoint.",
            83: "",
            84: "",
            85: "Asserts the midpoint 1.5.",
            86: "test_registry_contains_all_estimators: the registry is complete.",
            87: "The registry has exactly the three names.",
            88: "",
            89: "",
            90: "test_aggregate_dispatches_by_name: dispatch matches the direct calls.",
            91: "weighted_mean via aggregate.",
            92: "",
            93: "",
            94: "weighted_median via aggregate.",
            95: "weighted_trimmed_mean via aggregate.",
            96: "test_aggregate_unknown_estimator_raises: unknown names are rejected.",
            97: "Expects a ValueError mentioning the estimator.",
            98: "",
            99: "",
            100: "Calls with a nonsense estimator name.",
            101: "test_default_trim_frac_is_10_percent: the default is 10%.",
            102: "DEFAULT_TRIM_FRAC equals 0.10.",
            103: "",
            104: "",
            105: "The default trim reproduces the 105.625 example.",
            106: "test_trim_frac_over_half_falls_back_to_median: extreme trims fall back.",
            107: "Asserts the 0.9 trim result...",
            108: "",
            109: "",
            110: "...equals the weighted median.",
            111: "Closes the assert call.",
            112: "weighted_median over the A/B/C/D example.",
            113: "Closes the approx assertion.",
        },
    },
    # ── FILE 22: tests/test_metrics.py ──────────────────────────────────────────
    {
        "out": "28-test-metrics-py.html",
        "src": "tests/test_metrics.py",
        "title": "Walkthrough 28: tests/test_metrics.py",
        "prev": "27-test-estimators-py.html",
        "next": "29-price-predictor-py.html",
        "notes": {
            0: "Module docstring: tests for Phase E — metrics, synthetic data, and the report smoke.",
            1: "Imports numpy for NaN checks.",
            2: "Imports pandas for DataFrame handling.",
            3: "Imports pytest for assertions.",
            4: "",
            5: "Opens the metrics import block...",
            6: "AGGREGATION_ESTIMATORS, STABILITY_COLUMNS, aggregate_by_day.",
            7: "best_estimator_per_window, compare_aggregation_estimators.",
            8: "route_sensitivity, stability_stats, weight_elasticity.",
            9: "Closes the metrics import block.",
            10: "Imports the synthetic generator and its constants.",
            11: "Section header: stability stats tests.",
            12: "test_stability_stats_basic: checks the four metrics by hand.",
            13: "Comment: series [100, 105, 95, 100] → diffs [5, -10, 5].",
            14: "Scores that series with a threshold of 5.0.",
            15: "mean_abs_change = 20/3.",
            16: "",
            17: "",
            18: "std_change ≈ 8.660.",
            19: "",
            20: "max_abs_change = 10.0.",
            21: "extreme_move_days = 1.",
            22: "test_stability_stats_single_value: a single value has no moves.",
            23: "Scores a single-value series.",
            24: "mean is NaN (no diffs).",
            25: "No extreme days.",
            26: "test_stability_stats_with_nan_fills: NaNs are dropped first.",
            27: "",
            28: "",
            29: "Scores a series with a NaN in the middle.",
            30: "After dropping the NaN, the series is flat → move of 0.0.",
            31: "Section header: synthetic data tests.",
            32: "test_make_synthetic_shape_and_uniques: the generator's shape and content.",
            33: "",
            34: "",
            35: "Builds the default synthetic frame.",
            36: "All 12 routes are present.",
            37: "All three windows are present.",
            38: "",
            39: "",
            40: "15 unique dates overall (comment: all dates present across routes).",
            41: "",
            42: "504 rows total (comment: 12 routes × 14 dates × 3 windows).",
            43: "All fares are positive.",
            44: "Section header: aggregate-by-day tests.",
            45: "test_aggregate_by_day_series: extracts a usable daily series.",
            46: "Imports the index builders locally.",
            47: "Imports load_route_weights locally.",
            48: "Builds synthetic cleaned data.",
            49: "",
            50: "",
            51: "Collapses it to cell prices.",
            52: "",
            53: "Loads the real route weights.",
            54: "Computes the daily index.",
            55: "Extracts the window-1 aggregate series.",
            56: "",
            57: "The series is non-empty.",
            58: "Dates are monotonically increasing.",
            59: "Section header: aggregation-estimator comparison tests.",
            60: "test_compare_aggregation_estimators_keys_and_columns: the comparison map.",
            61: "Builds synthetic data.",
            62: "Imports the helpers locally.",
            63: "Collapses prices.",
            64: "",
            65: "",
            66: "Loads the route weights.",
            67: "",
            68: "Runs the comparison.",
            69: "All three estimators are present as keys.",
            70: "Loops over the tables...",
            71: "",
            72: "...each has all four stability columns.",
            73: "test_best_estimator_per_window_returns_all_windows: every window gets a pick.",
            74: "Builds synthetic data.",
            75: "Imports the helpers locally.",
            76: "Collapses prices.",
            77: "Loads the route weights.",
            78: "",
            79: "",
            80: "Runs the comparison.",
            81: "Picks the best estimator per window.",
            82: "All three windows are present.",
            83: "",
            84: "Loops over the picks...",
            85: "...each name is one of the aggregation estimators.",
            86: "Section header: route sensitivity tests.",
            87: "test_route_sensitivity_all_routes_and_robust: every route is scored, robustly.",
            88: "Builds synthetic data.",
            89: "Imports the helpers locally.",
            90: "Collapses prices.",
            91: "",
            92: "",
            93: "Loads the route weights.",
            94: "",
            95: "Computes sensitivity for window 1.",
            96: "Every weighted route appears in the output.",
            97: "Comment: losing one route's data moves the headline by well under 2 points.",
            98: "",
            99: "The maximum move is below 2.0.",
            100: "Comment: sorted descending.",
            101: "The scores are sorted descending.",
            102: "test_weight_elasticity_positive_and_ranked: leverage is positive, ranked.",
            103: "Builds synthetic data.",
            104: "Imports the helpers locally.",
            105: "Collapses prices.",
            106: "Loads the route weights.",
            107: "",
            108: "",
            109: "Computes elasticity for window 1.",
            110: "Every weighted route appears.",
            111: "All scores are positive.",
            112: "",
            113: "Comment: sorted descending, so the first route has the most leverage.",
            114: "The scores are sorted descending.",
            115: "Computes weight elasticity for lead window 1.",
            116: "Asserts the result index matches the weight keys.",
            117: "Asserts every elasticity is positive.",
            118: "Comment: sorted descending, so the first route has the most leverage.",
            119: "Asserts the elasticities come back sorted descending.",
        },
    },
    # ── FILE 23: src/models/price_predictor.py ──────────────────────────────────
    {
        "out": "29-price-predictor-py.html",
        "src": "src/models/price_predictor.py",
        "title": "Walkthrough 29: src/models/price_predictor.py",
        "prev": "28-test-metrics-py.html",
        "next": None,
        "notes": {
            0: "Module docstring: an airfare direction classifier neural network (Phase 2, standalone).",
            1: "",
            2: "Docstring: predicts whether a flight's fare will go DOWN, stay STABLE, or go UP...",
            3: "...at the next sampling point, given the cleaned row plus market context.",
            4: "",
            5: "Docstring: intentionally NOT wired into the MVP pipeline...",
            6: "...it exists as the open-ended Phase 2 model, imported nowhere in the app...",
            7: "...and depends on a future tensorflow install...",
            8: "...which is not in requirements.txt for the MVP.",
            9: "",
            10: "Docstring: architecture per the agreed spec...",
            11: "...input: 20 features (see FEATURES)...",
            12: "...hidden: 2 Dense layers, ReLU activation, Dropout(0.3) after each...",
            13: "...output: 3 units, Softmax over DOWN, STABLE, UP...",
            14: "Docstring: regularization — Dropout(0.3) + EarlyStopping with best weights restored.",
            15: "Closes the module docstring.",
            16: "",
            17: "Enables forward type annotations.",
            18: "",
            19: "Imports dataclass and field for the config dataclass.",
            20: "",
            21: "Imports Input and Model from tensorflow.keras.",
            22: "Imports the EarlyStopping callback.",
            23: "Imports Dense and Dropout layers.",
            24: "",
            25: "Comment: direction classes in output order (Softmax argmax index).",
            26: "CLASSES: the three output directions.",
            27: "",
            28: "N_FEATURES: the fixed 20-feature input size.",
            29: "",
            30: "Comment: ordered description of the 20 input features, following cleaned_flights names.",
            31: "Comment: derived fields are noted as such.",
            32: "Opens the FEATURES list...",
            33: "Fare features (normalised and derived).",
            34: "Continue: base_fare_scaled.",
            35: "taxes_scaled.",
            36: "fare_vs_route_avg — derived.",
            37: "fare_vs_carrier_avg — derived.",
            38: "lead_window_days_scaled.",
            39: "departure_hour_scaled.",
            40: "duration_mins_scaled.",
            41: "stops.",
            42: "route_index_current — derived.",
            43: "aggregate_index_current — derived.",
            44: "price_change_pct — derived.",
            45: "samples_seen — derived.",
            46: "is_weekend.",
            47: "Day-of-week one-hot features.",
            48: "dow_tue.",
            49: "dow_wed.",
            50: "dow_thu.",
            51: "dow_fri.",
            52: "dow_sat.",
            53: "Closes the FEATURES list.",
            54: "",
            55: "Runtime guard: the feature list must match N_FEATURES.",
            56: "",
            57: "",
            58: "Marks PredictorConfig as a frozen dataclass.",
            59: "Defines PredictorConfig: architecture and hyper-parameter defaults.",
            60: "Docstring.",
            61: "",
            62: "n_features, default 20.",
            63: "hidden_units — the two hidden layer sizes.",
            64: "hidden_activation — ReLU.",
            65: "dropout_rate — 0.3.",
            66: "n_classes — size of CLASSES (3).",
            67: "output_activation — softmax.",
            68: "learning_rate — 1e-3.",
            69: "early_stop_patience — 8 epochs.",
            70: "early_stop_min_delta — 1e-4.",
            71: "",
            72: "",
            73: "Defines build_predictor: constructs the Keras model.",
            74: "Docstring.",
            75: "Uses the given config, or defaults.",
            76: "",
            77: "The input layer: 20 features.",
            78: "First hidden Dense layer.",
            79: "First Dropout.",
            80: "Second hidden Dense layer.",
            81: "Second Dropout.",
            82: "The 3-unit softmax output layer.",
            83: "",
            84: "Assembles the functional model with a name.",
            85: "Compiles the model...",
            86: "...with the adam optimizer...",
            87: "...categorical crossentropy loss...",
            88: "...and accuracy metric.",
            89: "Closes the compile call.",
            90: "Returns the built model.",
            91: "",
            92: "",
            93: "Defines make_early_stopping: the callback used as a regularizer.",
            94: "Docstring.",
            95: "Uses the given config, or defaults.",
            96: "Opens the EarlyStopping constructor...",
            97: "...monitors validation loss...",
            98: "...patience from config...",
            99: "...min delta from config...",
            100: "...restores the best weights...",
            101: "...and is verbose.",
            102: "Closes the constructor.",
            103: "",
            104: "",
            105: "Defines train_predictor: fits the model with regularization.",
            106: "Parameter: the model to fit.",
            107: "Parameter: X — the feature matrix.",
            108: "Parameter: y — the one-hot labels.",
            109: "Parameter: keyword-only marker.",
            110: "Parameter: number of epochs (default 50).",
            111: "Parameter: batch size (default 32).",
            112: "Parameter: validation split (default 0.2).",
            113: "Parameter: optional config.",
            114: "Return type: the training history dict.",
            115: "Docstring (first part): fits with Dropout + EarlyStopping regularization.",
            116: "",
            117: "Docstring: pure training utility, not called in the MVP...",
            118: "...X is a (n, 20) feature matrix, y the one-hot label matrix...",
            119: "...returns the history.",
            120: "",
            121: "Docstring: NOTE — scrapped fare spans are heavily class-imbalanced...",
            122: "...(UP dominates), so add class weights when you get to Phase 2.",
            123: "Closes the docstring.",
            124: "Opens the model.fit call...",
            125: "...X...",
            126: "...y...",
            127: "...epochs...",
            128: "...batch size...",
            129: "...validation split...",
            130: "...the early-stopping callback...",
            131: "...verbose...",
            132: "Closes the fit call.",
            133: "Returns the history dict.",
            134: "Returns the Keras training-history dict for plotting/loss inspection.",
        },
    },
]

