"""Hand-written explanations for walkthrough files 09-12, 16, 21 (scraper).

Key = 0-based line number (line numbers shown in editors are 1-based, so
editor line N is key N-1). The generator verifies every key exists.
"""

FILES = [
    # ── FILE 9: src/scraper/base.py ────────────────────────────────────────
    {
        "out": "09-base-py.html",
        "src": "src/scraper/base.py",
        "title": "Walkthrough 9: src/scraper/base.py",
        "prev": "08-database-py.html",
        "next": "10-driver-py.html",
        "notes": {
            0: "ABC = Abstract Base Class; abstractmethod marks methods that subclasses MUST implement. This defines the scraper contract.",
            1: "Imports the date type for calendar-day arguments.",
            2: "",
            3: "Imports FlightRecord so every scraper knows the shape it must return.",
            4: "",
            5: "",
            6: "Defines BaseScraper as abstract — you cannot instantiate it directly.",
            7: "Docstring: the method every scraper must provide.",
            8: "",
            9: "Decorator marking the next method abstract (no body here).",
            10: "Declaration of the async method every scraper implements.",
            11: "Parameters: origin code, dest code, travel date, and lead-window days.",
            12: "Return type: a list of validated FlightRecord objects.",
            13: "Docstring describing the method's job.",
            14: "Ellipsis body — the concrete scraper supplies the real logic.",
        },
    },
    # ── FILE 10: src/scraper/driver.py ─────────────────────────────────────
    {
        "out": "10-driver-py.html",
        "src": "src/scraper/driver.py",
        "title": "Walkthrough 10: src/scraper/driver.py",
        "prev": "09-base-py.html",
        "next": "11-google-flights-py.html",
        "notes": {
            0: "asyncio gives us async/await for non-blocking browser I/O.",
            1: "logging for structured status and error messages.",
            2: "Decorator that turns an async generator into a context manager (async with).",
            3: "pathlib Path for readable, cross-platform file paths.",
            4: "",
            5: "PyYAML — reads config/scraper.yaml.",
            6: "Playwright async API: async_playwright launches browsers; Browser/BrowserContext/Page are type hints.",
            7: "",
            8: "Path to config/scraper.yaml: up 3 parents to the repo root, then into config/.",
            9: "Module-level logger; messages tagged with src.scraper.driver.",
            10: "",
            11: "",
            12: "Reads the scraper section of the config file.",
            13: "Open the file (with-block guarantees closing).",
            14: "Parse YAML and return only the scraper settings.",
            15: "",
            16: "",
            17: "Marks create_browser_context as an async context manager.",
            18: "Launches a browser, yields a context, then tears both down. Optional config override.",
            19: "Docstring, first line.",
            20: "",
            21: "Docstring: usage example start.",
            22: "Docstring: call notation.",
            23: "Docstring: create a page inside the context.",
            24: "Docstring: navigate somewhere.",
            25: "Docstring: closing quotes.",
            26: "Use the passed config or fall back to the YAML file.",
            27: "",
            28: "Start Playwright; async-with guarantees the driver shuts down.",
            29: "Launch a Chromium browser instance.",
            30: "Headless mode from config (default True = invisible).",
            31: "Close the launch call.",
            32: "Create an isolated browser context (like an incognito window).",
            33: "Configure the viewport (window size).",
            34: "Width from config, default 1280.",
            35: "Height from config, default 900.",
            36: "Close the viewport dict.",
            37: "Spoof a realistic Chrome user agent so we are not fingerprinted.",
            38: "Close new_context.",
            39: "Global action timeout: page_load_timeout is in seconds, x1000 to get ms.",
            40: "Log that the context is ready.",
            41: "try/finally guarantees cleanup even on error.",
            42: "Hand control to the caller — everything inside their async with runs here.",
            43: "finally block always runs.",
            44: "Close the context (tabs, storage, cookies).",
            45: "Close the browser process.",
            46: "Log the shutdown.",
        },
    },
    # ── FILE 11: src/scraper/google_flights.py (the big one) ───────────────
    {
        "out": "11-google-flights-py.html",
        "src": "src/scraper/google_flights.py",
        "title": "Walkthrough 11: src/scraper/google_flights.py",
        "prev": "10-driver-py.html",
        "next": "12-run-scrape-py.html",
        "notes": {
            0: "Module docstring, first line.",
            1: "",
            2: "Google Flights embeds a structured aria-label on every flight card.",
            3: "The label carries price, carrier, times, duration and stops in plain English.",
            4: "We parse that text instead of chasing fragile CSS class names.",
            5: "Close the docstring.",
            6: "asyncio — retries and delays are async.",
            7: "logging for diagnostics.",
            8: "random for human-looking jitter between requests.",
            9: "re — the regex engine behind all label parsing.",
            10: "date, datetime, timedelta for building times.",
            11: "pathlib for config paths.",
            12: "quote URL-encodes the search query safely.",
            13: "",
            14: "yaml reads our config files.",
            15: "Playwright async API: Page type + TimeoutError renamed PwTimeout to avoid clashing with builtins.TimeoutError.",
            16: "",
            17: "Our abstract scraper interface — guarantees we implement fetch_flights.",
            18: "Browser context launcher and config loader from driver.py.",
            19: "The Pydantic model we return.",
            20: "",
            21: "Module-level logger.",
            22: "",
            23: "Path to config/routes.yaml.",
            24: "",
            25: "Mapping of IATA codes to the city names used inside the search query.",
            26: "New Delhi.",
            27: "Mumbai.",
            28: "Bengaluru.",
            29: "Chennai.",
            30: "Close the mapping.",
            31: "",
            32: "",
            33: "Loads the routes YAML into a dict.",
            34: "Opens the file.",
            35: "Parses and returns the whole document.",
            36: "",
            37: "",
            38: "The concrete scraper. Inherits BaseScraper, so it must implement fetch_flights.",
            39: "Docstring for the class.",
            40: "",
            41: "Constructor: captures scraper settings from config.",
            42: "Keep the config dict for later use.",
            43: "Retry count per request.",
            44: "Backoff multiplier for exponential waits.",
            45: "Minimum random delay (seconds).",
            46: "Maximum random delay (seconds).",
            47: "Requests performed in the current rolling hour.",
            48: "Hourly request allowance.",
            49: "",
            50: "Section divider — public API.",
            51: "",
            52: "Public method required by BaseScraper. Adds retries + rate limiting around _scrape.",
            53: "self: instance reference.",
            54: "Origin airport code.",
            55: "Destination airport code.",
            56: "Travel date.",
            57: "Lead-window (days before departure).",
            58: "Return type: a list of FlightRecords.",
            59: "Seed value used for backoff waits.",
            60: "Remembers the last error to re-raise once retries are exhausted.",
            61: "",
            62: "Up to max_retries attempts.",
            63: "Wrap one attempt.",
            64: "Enforce the hourly rate limit first.",
            65: "Perform the actual scrape.",
            66: "Count this successful request.",
            67: "Success — return immediately.",
            68: "Handle Playwright timeouts distinctly.",
            69: "Record which exception occurred.",
            70: "Exponential backoff: base_delay then base_delay*2 then *4.",
            71: "Log the retry.",
            72: "Message format string.",
            73: "Log arguments.",
            74: "Close the log call.",
            75: "Sleep the backoff duration.",
            76: "Handle any other exception.",
            77: "Record it.",
            78: "Same backoff arithmetic.",
            79: "Log the retry with the error message.",
            80: "Format string including the exception.",
            81: "Log arguments.",
            82: "Close the log call.",
            83: "Sleep before retrying.",
            84: "",
            85: "All retries failed — log the permanent failure.",
            86: "Re-raise so run_scrape can count this route as failed.",
            87: "",
            88: "Section divider — internal methods.",
            89: "",
            90: "Rate limiter: keeps us under the hourly budget.",
            91: "Once at the ceiling...",
            92: "Log a warning.",
            93: "Wait a full 60 seconds.",
            94: "Reset the counter.",
            95: "Pick a random delay in [min, max).",
            96: "Sleep it to space out requests.",
            97: "",
            98: "One full scrape cycle for a route on a date.",
            99: "self.",
            100: "Origin.",
            101: "Destination.",
            102: "Travel date.",
            103: "Lead window.",
            104: "Returns parsed FlightRecords.",
            105: "Open a browser context (auto-closes on exit).",
            106: "Create a fresh page.",
            107: "Assemble the Google Flights URL.",
            108: "Log the URL.",
            109: "Navigate, waiting only for the DOM (JS may still be rendering).",
            110: "Wait for flight-card selectors.",
            111: "Extra jitter so prices finish rendering.",
            112: "",
            113: "Collect flight aria-labels via JS in the page.",
            114: "Log how many were found.",
            115: "",
            116: "Accumulator for parsed flights.",
            117: "Loop over every label.",
            118: "Parse the label into a FlightRecord (may be None).",
            119: "Arguments: label, route, date, window.",
            120: "Close the _parse_aria_label call.",
            121: "Only keep successfully parsed records.",
            122: "Append to the result list.",
            123: "",
            124: "Log how many valid flights we parsed.",
            125: "Return the records.",
            126: "",
            127: "Section divider — URL building.",
            128: "",
            129: "Static helper - called on the class, not an instance.",
            130: "Build the search URL for a route/date.",
            131: "Format the date as YYYY-MM-DD.",
            132: "City display name for origin (fall back to the IATA code).",
            133: "City display name for destination.",
            134: 'Natural-language query: "Flights from New Delhi to Mumbai on 2026-09-15".',
            135: "URL-encode the query, force English + INR, return the final URL.",
            136: "",
            137: "Section divider — waiting for results.",
            138: "",
            139: "Wait until flight results appear on the page.",
            140: "Candidate selectors to try in order (Google changes markup).",
            141: "Primary selector for flight-card list items.",
            142: "Fallback: any link-like div with flight in its aria-label.",
            143: "Fallback: partial class match on the list item.",
            144: "Last resort: plain list items inside a list role.",
            145: "Close the selector list.",
            146: "Try each selector.",
            147: "Guard one attempt.",
            148: "Wait up to 15 seconds for this selector.",
            149: "Log which selector succeeded.",
            150: "Results are rendered — stop.",
            151: "This selector timed out...",
            152: "...move on to the next.",
            153: "None matched: warn instead of failing (page may have no flights).",
            154: "",
            155: "Section divider — collecting aria-labels.",
            156: "",
            157: "Harvest flight aria-labels from the page.",
            158: "Docstring: explains the label source element.",
            159: "More docstring context.",
            160: "",
            161: "page.evaluate runs the JS directly in the browser — reliable than CSS scraping.",
            162: "Close the docstring.",
            163: "Run a JS snippet in the page; returns a list of strings.",
            164: "Anonymous JS function opening.",
            165: "Result array.",
            166: "Select every element carrying an aria-label.",
            167: "Read the label text.",
            168: "Keep only labels that mention both rupees and flight (real flight cards).",
            169: "Collect the match.",
            170: "Close the if.",
            171: "Close forEach and the querySelectorAll call.",
            172: "Return the labels to Python.",
            173: "Close the JS arrow function.",
            174: "Close the triple-quoted arg and the evaluate call.",
            175: "Hand the labels to our Python caller.",
            176: "",
            177: "Section divider — parsing one label.",
            178: "",
            179: "Turn one aria-label into a FlightRecord, or None.",
            180: "self.",
            181: "Raw aria-label text.",
            182: "Origin code.",
            183: "Destination code.",
            184: "Travel date (anchors the parsed times).",
            185: "Lead-window days.",
            186: "Return type: FlightRecord or None.",
            187: "Everything below is guarded so a bad label is just skipped.",
            188: "Extract price.",
            189: "Extract carrier.",
            190: "Extract stops.",
            191: "Extract departure time.",
            192: "Extract arrival time.",
            193: "Extract duration.",
            194: "",
            195: "Price and carrier are mandatory.",
            196: "Log the skip reason.",
            197: "Reject this label.",
            198: "",
            199: "A departure time is mandatory too.",
            200: "Log the skip reason.",
            201: "Reject.",
            202: "",
            203: "Convert the departure time string into a datetime on the travel date.",
            204: "",
            205: "If arrival text exists...",
            206: "...convert it the same way.",
            207: "Else if we know the duration...",
            208: "...arrival = departure + duration.",
            209: "Neither is available...",
            210: "...log it...",
            211: "...and reject.",
            212: "",
            213: "Overnight crossing check.",
            214: "If arrival precedes departure (red-eye), roll to the next day.",
            215: "",
            216: "Build the validated Pydantic record.",
            217: 'Route code like "DEL-BOM".',
            218: "Origin.",
            219: "Destination.",
            220: "Carrier.",
            221: "Labels rarely include the flight number, so we write N/A.",
            222: "Departure datetime.",
            223: "Arrival datetime.",
            224: "Duration in minutes (default 120 when unknown).",
            225: "Number of stops.",
            226: "Google Flights only exposes a total fare...",
            227: "...so base_fare stays 0.",
            228: "...and taxes stay 0.",
            229: "The parsed price becomes total_fare.",
            230: "Currency is INR.",
            231: "Lead-window days.",
            232: "Scrape timestamp = now.",
            233: "Close the constructor.",
            234: "Catch any parsing error.",
            235: "Debug-log it with the first 80 chars of the label.",
            236: "Return None — caller skips the record.",
            237: "",
            238: "Section divider — the field extractors.",
            239: "",
            240: "Static helper.",
            241: "Pull the price out of a label.",
            242: 'Docstring: example of the source text.',
            243: 'Regex: "From <digits> Indian rupees".',
            244: "If matched...",
            245: "...strip commas and parse to int.",
            246: 'Fallback regex: digits followed by optional "Indian" and "rupees".',
            247: "If matched...",
            248: "...same cleanup.",
            249: "No price found in the label.",
            250: "",
            251: "Static helper.",
            252: "Pull the airline name out of a label.",
            253: 'Docstring: example.',
            254: 'Regex: capture the text after "with" up to a period, "Leaves", or end-of-string.',
            255: "If matched...",
            256: "...return the carrier, whitespace-trimmed.",
            257: "No carrier parsed.",
            258: "",
            259: "Static helper.",
            260: "Determine the number of stops.",
            261: 'Docstring: examples.',
            262: "Lowercase the label for case-insensitive checks.",
            263: '"nonstop" or "non-stop" means 0 stops.',
            264: "Return 0 stops.",
            265: 'Regex: "<digits> stop(s)".',
            266: "If matched...",
            267: "...return the stop count.",
            268: "Default to 0 stops.",
            269: "",
            270: "Static helper.",
            271: "Extract a departure or arrival time.",
            272: "Docstring line 1.",
            273: 'Docstring line 2: the expected phrase pattern.',
            274: 'Regex: find times preceded by "at".',
            275: "If none found...",
            276: "...fall back to matching any standalone time.",
            277: "With at least two times...",
            278: "...first = departure, second = arrival.",
            279: "With exactly one time...",
            280: "...log the ambiguity...",
            281: "...return None (can't tell which it is).",
            282: "No usable times.",
            283: "",
            284: "Static helper.",
            285: "Parse the duration into minutes.",
            286: 'Docstring: example.',
            287: 'Regex: "Total duration <hrs> hr <mins> min".',
            288: "If matched...",
            289: "Hours from group 1.",
            290: "Minutes from group 2 (default 0).",
            291: "Total minutes.",
            292: "Fallback: any '<hrs> hr <mins> min' substring.",
            293: "If matched...",
            294: "Hours.",
            295: "Minutes.",
            296: "Total minutes.",
            297: "No duration parsed.",
            298: "",
            299: "Section divider — shared helpers.",
            300: "",
            301: "Static helper.",
            302: "Convert a time string plus a date into a datetime.",
            303: "Normalise: trim whitespace, convert 8.45 -> 8:45.",
            304: 'Try formats: 12h with space, 12h without space, 24h.',
            305: "Guard each format attempt.",
            306: "Parse the clock string.",
            307: "Combine the clock time with the travel date.",
            308: "This format did not match...",
            309: "...try the next one.",
            310: "No format matched: default to midnight on the travel date.",
            311: "",
            312: "Static async helper.",
            313: "Sleep a uniform random amount between lo and hi seconds.",
        },
    },
    # ── FILE 12: src/scraper/run_scrape.py ─────────────────────────────────
    {
        "out": "12-run-scrape-py.html",
        "src": "src/scraper/run_scrape.py",
        "title": "Walkthrough 12: src/scraper/run_scrape.py",
        "prev": "11-google-flights-py.html",
        "next": "13-clean-py.html",
        "notes": {
            0: "Module docstring: purpose.",
            1: "",
            2: "Usage section.",
            3: "Run all routes for today.",
            4: "Run for a specific date.",
            5: "Close the docstring.",
            6: "argparse for the --date flag.",
            7: "asyncio for the async scraper.",
            8: "logging.",
            9: "sys for stdout logging handlers.",
            10: "Date helpers.",
            11: "Path for file locations.",
            12: "",
            13: "yaml to read routes config.",
            14: "",
            15: "The scraper class and its route loader.",
            16: "FlightRecord type for the insert helper.",
            17: "SQLite connection helpers.",
            18: "",
            19: "Module logger.",
            20: "",
            21: "",
            22: "Configures console logging for this run.",
            23: "Set the root logger level.",
            24: "Show INFO and above.",
            25: "Log format: time | level | module | message.",
            26: "Time format.",
            27: "Write to stdout.",
            28: "Close basicConfig.",
            29: "",
            30: "",
            31: "Batch-inserts FlightRecords into raw_flights.",
            32: "Docstring. Returns the number of rows inserted.",
            33: "Nothing to insert — early out.",
            34: "Return 0.",
            35: "",
            36: "Open a connection (default database).",
            37: "Guarantee the connection closes.",
            38: "SQL insert statement (multiline, opened).",
            39: "Table name.",
            40: "Column list (first part).",
            41: "Column list (second part).",
            42: "Column list (third part).",
            43: "Column list (fourth part).",
            44: "16 placeholders for 16 columns.",
            45: "Close the SQL string.",
            46: "Build the parameter rows.",
            47: "One tuple per FlightRecord.",
            48: "Scrape date first.",
            49: "Route fields.",
            50: "Carrier and flight number.",
            51: "Departure as ISO string.",
            52: "Arrival as ISO string.",
            53: "Numeric fields.",
            54: "Monetary fields.",
            55: "Currency and lead window.",
            56: "Scrape timestamp as ISO string.",
            57: "Close the tuple.",
            58: "Comprehension: one tuple per record.",
            59: "Close the rows list.",
            60: "Bulk-execute all inserts.",
            61: "Commit the transaction.",
            62: "Return the inserted count.",
            63: "finally always runs.",
            64: "Close the connection.",
            65: "",
            66: "",
            67: "Main async orchestrator.",
            68: "Docstring: every route x every day offset in the horizon.",
            69: "Configure logging.",
            70: "Ensure tables exist.",
            71: "",
            72: "Load the routes config.",
            73: "The 12 directional routes.",
            74: "Horizon in days from config, default 30.",
            75: "Day offsets 1..horizon — the departure dates (lead windows) to scrape.",
            76: "Scrape-date stamp (defaults to today).",
            77: "",
            78: "Log the run start.",
            79: "Log the basket size: 12 routes x horizon days.",
            80: "",
            81: "Instantiate the scraper.",
            82: "Running total of inserted rows.",
            83: "Failure counter.",
            84: "",
            85: "Iterate routes.",
            86: "Unpack origin/dest.",
            87: "Iterate day offsets — a request per departure date.",
            88: "Travel date = scrape date + offset.",
            89: "Log progress.",
            90: "",
            91: "Guard one scrape.",
            92: "Fetch and parse records.",
            93: "Persist them.",
            94: "Accumulate count.",
            95: "Log success.",
            96: "On failure...",
            97: "...count it and...",
            98: "...log the error.",
            99: "",
            100: "Final summary log (opened).",
            101: "Summary format string (routeXday instead of route x window).",
            102: "Arguments.",
            103: "Close the log call.",
            104: "",
            105: "",
            106: "CLI entry point.",
            107: "Argument parser.",
            108: "--date flag.",
            109: "Help text.",
            110: "Parse args.",
            111: "",
            112: "Convert the date string, or None.",
            113: "Run the async pipeline.",
            114: "",
            115: "",
            116: "Run only when executed directly.",
            117: "Call main.",
        },
    },
    # ── FILE 16: src/scraper/run_smoke.py ──────────────────────────────────
    {
        "out": "16-run-smoke-py.html",
        "src": "src/scraper/run_smoke.py",
        "title": "Walkthrough 16: src/scraper/run_smoke.py",
        "prev": "15-api-index-py.html",
        "next": "17-pipeline-py.html",
        "notes": {
            0: "Module docstring: one-route smoke test.",
            1: "",
            2: "Docstring: run interactively, hits the live site.",
            3: "The command to run it.",
            4: "Close the docstring.",
            5: "asyncio for the async scraper.",
            6: "sys: lets us inject the repo root for imports.",
            7: "pathlib to build paths.",
            8: "Date helpers.",
            9: "",
            10: "Insert the project root at the front of sys.path so src.* imports resolve.",
            11: "",
            12: "The scraper class.",
            13: "Reuse run_scrape's batch-insert helper.",
            14: "Database init.",
            15: "",
            16: "",
            17: "Async test routine.",
            18: "Create tables.",
            19: "Instantiate the scraper.",
            20: "Travel date: 7 days from now.",
            21: "Print what we are testing.",
            22: "",
            23: "Scrape DEL -> BOM for the window-7 date.",
            24: "Report how many flights we got.",
            25: "",
            26: "Print the first five flights.",
            27: "Open the print call.",
            28: "Rank + carrier + fare.",
            29: "Duration + stops.",
            30: "Departure time.",
            31: "Arrival time.",
            32: "Close the print call.",
            33: "",
            34: "If we got any records...",
            35: "...persist them under today's date.",
            36: "...report the inserted row count.",
            37: "",
            38: "",
            39: "Run only when executed directly.",
            40: "Launch the async test.",
        },
    },
    # ── FILE 21: src/test_scraper.py ───────────────────────────────────────
    {
        "out": "21-test-scraper-py.html",
        "src": "src/test_scraper.py",
        "title": "Walkthrough 21: src/test_scraper.py",
        "prev": "20-test-run-py.html",
        "next": "22-test-indexer-py.html",
        "notes": {
            0: "Module docstring: tests the scraper on one route.",
            1: "asyncio.",
            2: "sys for path injection.",
            3: "pathlib for paths.",
            4: "Date helpers.",
            5: "",
            6: "Insert the repo root (parent.parent of src/) into sys.path.",
            7: "",
            8: "The scraper class.",
            9: "The insert helper from run_scrape.",
            10: "Database init.",
            11: "",
            12: "",
            13: "Async test routine.",
            14: "Create tables.",
            15: "Instantiate the scraper.",
            16: "Travel date: 7 days from now.",
            17: "Print the test target.",
            18: "",
            19: "Scrape DEL -> BOM.",
            20: "Report the number of flights.",
            21: "",
            22: "Print the first five.",
            23: "Open the print.",
            24: "Rank + carrier + fare.",
            25: "Duration + stops.",
            26: "Departure.",
            27: "Arrival.",
            28: "Close the print.",
            29: "",
            30: "If records exist...",
            31: "...insert them for today.",
            32: "...report the count.",
            33: "",
            34: "",
            35: "Run only when executed directly.",
            36: "Launch the test.",
        },
    },
]