"""Hand-written explanations for walkthrough files 13, 17-20 (Phase 2: cleaning).

Each dict maps a 0-based LINE NUMBER to the plain-English explanation that will
be rendered under that line. The code itself is read from the source file at
build time, so the dicts below must cover every line.
"""

FILES = [
    # ── FILE 13: src/cleaner/clean.py ────────────────────────────────────────
    {
        "out": "13-clean-py.html",
        "src": "src/cleaner/clean.py",
        "title": "Walkthrough 13: src/cleaner/clean.py",
        "prev": "12-run-scrape-py.html",
        "next": "14-run-index-py.html",
        "notes": {
            0: "Imports hashlib for dedup hashing.",
            1: "Imports logging for status messages.",
            2: "Imports sys for stdout-based logging handler.",
            3: "Imports Path for filesystem-agnostic config resolution.",
            4: "",
            5: "Imports pandas for all DataFrame operations.",
            6: "Imports yaml to load the indexer config file.",
            7: "",
            8: "Creates a module-level logger.",
            9: "",
            10: "Resolves the path to config/indexer.yaml relative to the project root.",
            11: "",
            12: "",
            13: "Defines _load_cleaning_config: reads the cleaning section from indexer.yaml.",
            14: "Falls back to the default CONFIG_PATH if no custom path is supplied.",
            15: "Opens the YAML file.",
            16: "Parses it into a Python dict.",
            17: "Returns only the 'cleaning' sub-dict (iqr_multiplier, null_fare_action).",
            18: "",
            19: "",
            20: "Defines _compute_hash: builds a dedup key from five fare-identifying fields.",
            21: "Concatenates route, carrier, depart_time, total_fare, and lead_window_days with pipe separators.",
            22: "Hashes the composite key with MD5 and returns the hex digest.",
            23: "",
            24: "",
            25: "Defines _flag_outliers_iqr: marks fares outside 1.5x IQR as outliers.",
            26: "First quartile of the fare group.",
            27: "Third quartile of the fare group.",
            28: "Interquartile range (Q3 - Q1).",
            29: "Lower fence = Q1 minus multiplier times IQR.",
            30: "Upper fence = Q3 plus multiplier times IQR.",
            31: "Returns 1 for outlier rows, 0 for normal rows.",
            32: "",
            33: "",
            34: "Defines _compute_quality_score: starts at 1.0, penalises missing fields.",
            35: "Initial score of 1.0 for every row.",
            36: "Loops over five critical columns.",
            37: "Deducts 0.2 from the score wherever a value is missing.",
            38: "Deducts 0.1 if stops is not in {0, 1, 2}.",
            39: "Clips the final score between 0 and 1.",
            40: "",
            41: "",
            42: "Defines clean_raw_data: the main cleaning entry point.",
            43: "Accepts an optional db_path override.",
            44: "Accepts an optional cfg_path override.",
            45: "Returns a dict of cleaning statistics.",
            46: "Adds the project root to sys.path so database.py can be imported.",
            47: "Imports DB_PATH and get_connection from the storage layer.",
            48: "",
            49: "Resolves the database file path; falls back to the default DB_PATH.",
            50: "Loads the cleaning configuration from YAML.",
            51: "",
            52: "Reads the IQR multiplier (default 1.5).",
            53: "Reads the null-fare strategy: 'drop' or 'ffill'.",
            54: "",
            55: "Logs which database file is being read.",
            56: "Opens a SQLite connection.",
            57: "Loads the entire raw_flights table into a DataFrame.",
            58: "Closes the connection immediately after reading.",
            59: "",
            60: "Early exit path if the table is empty.",
            61: "Logs a warning.",
            62: "Returns zeros for all statistics when there is nothing to clean.",
            63: "",
            64: "Records the initial row count for the stats dict.",
            65: "Logs how many raw rows were loaded.",
            66: "",
            67: "Computes a dedup hash for each row using the five-field composite key.",
            68: "Saves the pre-dedup row count.",
            69: "Removes exact hash duplicates, keeping the first occurrence.",
            70: "Calculates how many duplicates were removed.",
            71: "Logs the dedup count.",
            72: "",
            73: "Branches on the null-fare strategy from config.",
            74: "Drop path: records the count before dropping.",
            75: "Drops rows where total_fare is null.",
            76: "Counts how many were dropped.",
            77: "Logs the result.",
            78: "Forward-fill path: sorts by route, window, and scrape timestamp.",
            79: "Forward-fills null fares within each route-plus-window group.",
            80: "Closes the transform call.",
            81: "Counts any remaining nulls after forward-fill.",
            82: "Drops rows that still have no fare after ffill.",
            83: "Logs the forward-fill result.",
            84: "",
            85: "Begins the IQR outlier flagging block.",
            86: "Groups by route and lead window.",
            87: "Applies the IQR outlier function within each group.",
            88: "Closes the transform call.",
            89: "Counts total flagged outliers.",
            90: "Logs the outlier count and the multiplier used.",
            91: "",
            92: "Computes the per-row quality score.",
            93: "Extracts scrape_date as a date string from the timestamp.",
            94: "Normalises scrape_timestamp to YYYY-MM-DD HH:MM:SS format.",
            95: "Normalises depart_time with coerce for invalid date strings.",
            96: "Normalises arrive_time with coerce for invalid date strings.",
            97: "",
            98: "Begins the list of columns to keep in cleaned_flights.",
            99: "First row of column names: scrape_date through flight_no.",
            100: "Second row: depart_time through stops.",
            101: "Third row: base_fare through lead_window_days.",
            102: "Fourth row: scrape_timestamp through dedup_hash.",
            103: "Closes the keep_cols list.",
            104: "Selects only the keep_cols from the DataFrame.",
            105: "",
            106: "Logs the number of rows being written.",
            107: "Opens a new SQLite connection for writing.",
            108: "Appends cleaned rows to the cleaned_flights table.",
            109: "Closes the write connection.",
            110: "",
            111: "Assembles the stats dictionary.",
            112: "Raw row count.",
            113: "Cleaned row count.",
            114: "Number of duplicates removed.",
            115: "Number of outliers flagged.",
            116: "Number of null-fare rows removed.",
            117: "Closes the stats dict.",
            118: "Logs the final statistics.",
            119: "Returns the stats dict to the caller.",
            120: "",
            121: "",
            122: "Script entry point when run directly via python clean.py.",
            123: "Configures logging to stdout.",
            124: "Log level set to INFO.",
            125: "Format includes timestamp, level, and message.",
            126: "Time format HH:MM:SS.",
            127: "Outputs to stdout via StreamHandler.",
            128: "Closes the basicConfig call.",
            129: "",
            130: "Calls clean_raw_data with default paths.",
            131: "Prints the returned stats dict.",
            132: "Closes the f-string.",
        },
    },
    # ── FILE 17: src/cleaner/pipeline.py ──────────────────────────────────────
    {
        "out": "17-pipeline-py.html",
        "src": "src/cleaner/pipeline.py",
        "title": "Walkthrough 17: src/cleaner/pipeline.py",
        "prev": "16-run-smoke-py.html",
        "next": "18-mock-data-py.html",
        "notes": {
            0: "Imports hashlib for MD5 dedup hashing.",
            1: "Imports pandas for DataFrame operations.",
            2: "Imports sqlalchemy create_engine for SQLite writes.",
            3: "",
            4: "",
            5: "Defines cast_types: coerces raw DataFrame columns to correct dtypes.",
            6: "Works on a copy to avoid mutating the caller's DataFrame.",
            7: "Casts total_fare to float for numeric operations.",
            8: "Comment: errors='coerce' turns unparseable dates into NaT instead of failing.",
            9: "Casts the date column to datetime, coercing bad values.",
            10: "Casts stops to nullable integer (Int64 supports NaN).",
            11: "Casts duration_mins to nullable integer.",
            12: "Fills missing is_cancellation with False, then casts to bool.",
            13: "Returns the cast DataFrame.",
            14: "",
            15: "",
            16: "Defines deduplicate: removes duplicate flight records via MD5 hash.",
            17: "Works on a copy.",
            18: "",
            19: "Comment: checks for depart_time column to handle N/A flight numbers.",
            20: "Builds the depart_time string component, or empty string if column is absent.",
            21: "",
            22: "Begins the composite dedup key construction.",
            23: "Route component.",
            24: "Pipe separator.",
            25: "Carrier component.",
            26: "Pipe separator.",
            27: "Flight number component.",
            28: "Pipe separator.",
            29: "Date component.",
            30: "Pipe separator.",
            31: "Depart_time component (safeguard for flight_no = N/A).",
            32: "Closes the key tuple.",
            33: "Hashes each key string with MD5.",
            34: "Drops duplicate hashes, keeping the first occurrence.",
            35: "Drops the temporary dedup_hash column and returns.",
            36: "",
            37: "",
            38: "Defines filter_unavailable: removes sold-out and cancelled flights.",
            39: "Works on a copy.",
            40: "Keeps rows where status is not 'sold_out' and is_cancellation is False.",
            41: "Returns the filtered DataFrame.",
            42: "",
            43: "",
            44: "Defines handle_nulls: drops rows with no fare, fills missing carriers.",
            45: "Works on a copy.",
            46: "Drops rows where total_fare is null.",
            47: "Fills missing carrier values with 'UNKNOWN'.",
            48: "Returns the cleaned DataFrame.",
            49: "",
            50: "",
            51: "Defines flag_outliers: marks extreme fares via per-route IQR.",
            52: "Works on a copy.",
            53: "Groups total_fare by route.",
            54: "Computes Q1 within each route group.",
            55: "Computes Q3 within each route group.",
            56: "Calculates the interquartile range.",
            57: "Lower fence at Q1 minus 1.5 times IQR.",
            58: "Upper fence at Q3 plus 1.5 times IQR.",
            59: "",
            60: "Comment: NaN outlier evaluations are filled with False for low-count routes.",
            61: "Builds the outlier boolean mask.",
            62: "Fills NaN with False and assigns to is_outlier column.",
            63: "Returns the flagged DataFrame.",
            64: "",
            65: "",
            66: "Defines clean_flights: orchestrates the full cleaning pipeline.",
            67: "Step 1: cast column types.",
            68: "Step 2: deduplicate rows.",
            69: "Step 3: filter out sold-out and cancelled flights.",
            70: "Step 4: handle null fares and carriers.",
            71: "Step 5: flag IQR outliers.",
            72: "Returns the fully cleaned DataFrame.",
            73: "",
            74: "",
            75: "Defines write_cleaned: writes cleaned_flights to SQLite via SQLAlchemy.",
            76: "Creates a SQLAlchemy engine for the target database.",
            77: "Comment: engine.begin() context manager ensures a clean commit.",
            78: "Opens a transactional connection.",
            79: "Writes the DataFrame to the cleaned_flights table.",
            80: "Disposes the engine to release the connection pool.",
        },
    },
    # ── FILE 18: src/cleaner/mock_data.py ─────────────────────────────────────
    {
        "out": "18-mock-data-py.html",
        "src": "src/cleaner/mock_data.py",
        "title": "Walkthrough 18: src/cleaner/mock_data.py",
        "prev": "17-pipeline-py.html",
        "next": "19-check-db-py.html",
        "notes": {
            0: "Imports os for file existence checks.",
            1: "Imports random for reproducible fake data generation.",
            2: "",
            3: "Imports pandas for DataFrame construction.",
            4: "Imports sqlalchemy create_engine for writing mock databases.",
            5: "",
            6: "ROUTES: 12 directional city-pair routes from Delhi.",
            7: "Second row of routes.",
            8: "Third row of routes.",
            9: "Fourth row of routes.",
            10: "Closes the ROUTES list.",
            11: "",
            12: "CARRIER_CODES: five Indian airline IATA codes.",
            13: "",
            14: "BASE_DATE: the reference date for generating 30-day fare windows.",
            15: "",
            16: "EXTREME_FARES: deliberately extreme values to test outlier detection.",
            17: "",
            18: "",
            19: "Defines build_mock_df: creates a realistic DataFrame with deliberate defects.",
            20: "Seeds the random generator for reproducibility.",
            21: "Initialises the row accumulator.",
            22: "Loops over each of the 12 routes.",
            23: "Random base fare between 3200 and 5200.",
            24: "Loops over 30 days of lead window.",
            25: "Adds random variation of up to 900 to the base fare.",
            26: "First 3 days get a 2-4x surge multiplier (simulate last-minute pricing).",
            27: "Applies the surge multiplier.",
            28: "Days 4-10 get a 1.3-1.8x multiplier (near-term premium).",
            29: "Applies the near-term multiplier.",
            30: "Picks a random carrier for this row.",
            31: "Appends a flight record dict.",
            32: "Route field.",
            33: "Carrier field.",
            34: "Flight number: carrier code plus 3-digit random number.",
            35: "Date field: offset from BASE_DATE.",
            36: "Total fare rounded to 2 decimals.",
            37: "Stops: weighted toward 0 and 1.",
            38: "Duration between 95 and 240 minutes.",
            39: "Status is 'available' for normal rows.",
            40: "Not a cancellation.",
            41: "Closes the row dict.",
            42: "Closes the route loop and builds a DataFrame.",
            43: "",
            44: "Adds 15 duplicate rows to test deduplication.",
            45: "",
            46: "Samples 10 rows and marks them as sold_out.",
            47: "Sets status to 'sold_out'.",
            48: "Appends the sold-out rows.",
            49: "",
            50: "Samples 6 rows and marks them as cancellations.",
            51: "Sets is_cancellation to True.",
            52: "Appends the cancelled rows.",
            53: "",
            54: "Samples 8 rows and nullifies their fares.",
            55: "Sets total_fare to NaN.",
            56: "Appends the null-fare rows.",
            57: "",
            58: "Samples 6 rows and nullifies their carriers.",
            59: "Sets carrier to None.",
            60: "Appends the null-carrier rows.",
            61: "",
            62: "Creates outlier rows with extreme fares from EXTREME_FARES.",
            63: "Dict for each outlier row.",
            64: "Random route.",
            65: "Random carrier.",
            66: "Fixed flight number XX900.",
            67: "Fixed date: 2 days after BASE_DATE.",
            68: "Fare from the EXTREME_FARES list.",
            69: "Random stops.",
            70: "Random duration.",
            71: "Status available.",
            72: "Not a cancellation.",
            73: "Closes the dict literal.",
            74: "List comprehension iterates over all extreme fares.",
            75: "Closes the DataFrame constructor.",
            76: "Appends the outlier rows.",
            77: "",
            78: "Shuffles all rows randomly and resets the index.",
            79: "",
            80: "",
            81: "Defines build_mock_db: creates a fresh SQLite database with mock data.",
            82: "Checks if the database file already exists.",
            83: "Deletes the existing file to start fresh.",
            84: "Builds the mock DataFrame.",
            85: "Creates a SQLAlchemy engine.",
            86: "Writes the DataFrame to the raw_flights table, replacing any existing data.",
            87: "Disposes the engine.",
            88: "Returns the mock DataFrame for inspection.",
        },
    },
    # ── FILE 19: src/cleaner/check_db.py ──────────────────────────────────────
    {
        "out": "19-check-db-py.html",
        "src": "src/cleaner/check_db.py",
        "title": "Walkthrough 19: src/cleaner/check_db.py",
        "prev": "18-mock-data-py.html",
        "next": "20-test-run-py.html",
        "notes": {
            0: "Imports sqlite3 for direct database access.",
            1: "Imports pandas for SQL query execution.",
            2: "",
            3: "Opens the default flights.db database.",
            4: "Creates a persistent connection.",
            5: "",
            6: "Prints the header for the record count comparison.",
            7: "Runs a SQL query comparing raw and cleaned row counts.",
            8: "SELECT keyword.",
            9: "Subquery: count of raw_flights rows.",
            10: "Subquery: count of cleaned_flights rows.",
            11: "Subquery: difference between raw and cleaned counts.",
            12: "Closes the SQL string and passes the connection.",
            13: "Prints the count comparison table.",
            14: "",
            15: "Prints the header for the outlier check.",
            16: "Runs a query counting rows by is_outlier flag.",
            17: "Selects is_outlier and its count.",
            18: "From the cleaned_flights table.",
            19: "Groups by the is_outlier column.",
            20: "Closes the SQL string.",
            21: "Prints the outlier distribution.",
            22: "",
            23: "Prints the header for the null-values audit.",
            24: "Loads the entire cleaned_flights table into a DataFrame.",
            25: "Counts null values per column.",
            26: "Renames columns for readability.",
            27: "Prints the null-count table.",
            28: "",
            29: "Prints the header for the fare summary comparison.",
            30: "Runs a UNION ALL query comparing raw vs cleaned fare statistics.",
            31: "Raw table stats: average, min, max fare.",
            32: "UNION ALL separator.",
            33: "Cleaned table stats: average, min, max fare.",
            34: "Closes the SQL string.",
            35: "Prints the fare comparison table.",
            36: "",
            37: "Closes the database connection.",
        },
    },
    # ── FILE 20: src/cleaner/test_run.py ──────────────────────────────────────
    {
        "out": "20-test-run-py.html",
        "src": "src/cleaner/test_run.py",
        "title": "Walkthrough 20: src/cleaner/test_run.py",
        "prev": "19-check-db-py.html",
        "next": "21-test-scraper-py.html",
        "notes": {
            0: "Imports pandas for DataFrame operations.",
            1: "Imports sqlalchemy create_engine for database access.",
            2: "",
            3: "Imports build_mock_db from the local mock_data module.",
            4: "Imports clean_flights and write_cleaned from the local pipeline module.",
            5: "",
            6: "Target database path for the mock database.",
            7: "",
            8: "Step 1 comment: initialise or reset the mock database.",
            9: "Creates a fresh flights.db with synthetic raw_flights data.",
            10: "",
            11: "Step 2 comment: extract raw data using a context manager.",
            12: "Creates a SQLAlchemy engine.",
            13: "Opens a connection via context manager.",
            14: "Reads the entire raw_flights table into a DataFrame.",
            15: "Disposes the engine to close the pool.",
            16: "",
            17: "Step 3 comment: clean raw records via the Phase 2 pipeline.",
            18: "Records the raw row count.",
            19: "Runs the full cleaning pipeline on the raw DataFrame.",
            20: "",
            21: "Step 4 comment: save cleaned output to SQLite.",
            22: "Writes cleaned_flights to the database.",
            23: "",
            24: "Step 5 comment: define deduplication keys for the audit.",
            25: "Base dedup keys: route, carrier, flight_no, date.",
            26: "Checks if depart_time is present in the cleaned data.",
            27: "Appends depart_time to the dedup key list if present.",
            28: "",
            29: "Step 6 comment: audit and log the execution summary.",
            30: "Prints the summary header.",
            31: "Prints the raw row count.",
            32: "Prints the cleaned row count.",
            33: "Prints the number of rows removed.",
            34: "Prints the number of outliers flagged.",
            35: "Prints remaining null fares.",
            36: "Prints remaining duplicates based on dedup keys.",
            37: "Prints remaining sold-out rows (should be 0 after filtering).",
            38: "Prints remaining cancellations (should be 0 after filtering).",
            39: "Prints the number of unique routes in cleaned data.",
            40: "Prints the dtypes of all cleaned columns for verification.",
        },
    },
]
